{
  "kind": "discovery#restDescription",
  "etag": "\"9eZ1uxVRThTDhLJCZHhqs3eQWz4/zc7BVZTngzEcCz2hafit0Wqy0Pg\"",
  "discoveryVersion": "v1",
  "id": "adsense:v1.4",
  "name": "adsense",
  "canonicalName": "AdSense",
  "fullyEncodeReservedExpansion": null,
  "version": "v1.4",
  "revision": "20190820",
  "title": "AdSense Management API",
  "description": "Accesses AdSense publishers' inventory and generates performance reports.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/adsense/management/",
  "protocol": "rest",
  "baseUrl": "https://www.googleapis.com/adsense/v1.4/",
  "basePath": "/adsense/v1.4/",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "adsense/v1.4/",
  "batchPath": "batch/adsense/v1.4",
  "version_module": null,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        }
      }
    }
  },
  "resources": {
    "accounts": {
      "resources": {
        "adclients": {
          "resources": {},
          "methods": {
            "getAdCode": {
              "id": "adsense.accounts.adclients.getAdCode",
              "path": "accounts/{accountId}/adclients/{adClientId}/adcode",
              "httpMethod": "GET",
              "description": "Get Auto ad code for a given ad client.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "adsense.accounts.adclients.list",
              "path": "accounts/{accountId}/adclients",
              "httpMethod": "GET",
              "description": "List all ad clients in the specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "adunits": {
          "resources": {
            "customchannels": {
              "resources": {},
              "methods": {
                "list": {
                  "id": "adsense.accounts.adunits.customchannels.list",
                  "path": "accounts/{accountId}/adclients/{adClientId}/adunits/{adUnitId}/customchannels",
                  "httpMethod": "GET",
                  "description": "List all custom channels which the specified ad unit belongs to.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "get": {
              "id": "adsense.accounts.adunits.get",
              "path": "accounts/{accountId}/adclients/{adClientId}/adunits/{adUnitId}",
              "httpMethod": "GET",
              "description": "Gets the specified ad unit in the specified ad client for the specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "getAdCode": {
              "id": "adsense.accounts.adunits.getAdCode",
              "path": "accounts/{accountId}/adclients/{adClientId}/adunits/{adUnitId}/adcode",
              "httpMethod": "GET",
              "description": "Get ad code for the specified ad unit.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "adsense.accounts.adunits.list",
              "path": "accounts/{accountId}/adclients/{adClientId}/adunits",
              "httpMethod": "GET",
              "description": "List all ad units in the specified ad client for the specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "alerts": {
          "resources": {},
          "methods": {
            "delete": {
              "id": "adsense.accounts.alerts.delete",
              "path": "accounts/{accountId}/alerts/{alertId}",
              "httpMethod": "DELETE",
              "description": "Dismiss (delete) the specified alert from the specified publisher AdSense account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "adsense.accounts.alerts.list",
              "path": "accounts/{accountId}/alerts",
              "httpMethod": "GET",
              "description": "List the alerts for the specified AdSense account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "customchannels": {
          "resources": {
            "adunits": {
              "resources": {},
              "methods": {
                "list": {
                  "id": "adsense.accounts.customchannels.adunits.list",
                  "path": "accounts/{accountId}/adclients/{adClientId}/customchannels/{customChannelId}/adunits",
                  "httpMethod": "GET",
                  "description": "List all ad units in the specified custom channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "get": {
              "id": "adsense.accounts.customchannels.get",
              "path": "accounts/{accountId}/adclients/{adClientId}/customchannels/{customChannelId}",
              "httpMethod": "GET",
              "description": "Get the specified custom channel from the specified ad client for the specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "adsense.accounts.customchannels.list",
              "path": "accounts/{accountId}/adclients/{adClientId}/customchannels",
              "httpMethod": "GET",
              "description": "List all custom channels in the specified ad client for the specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "payments": {
          "resources": {},
          "methods": {
            "list": {
              "id": "adsense.accounts.payments.list",
              "path": "accounts/{accountId}/payments",
              "httpMethod": "GET",
              "description": "List the payments for the specified AdSense account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "reports": {
          "resources": {
            "saved": {
              "resources": {},
              "methods": {
                "generate": {
                  "id": "adsense.accounts.reports.saved.generate",
                  "path": "accounts/{accountId}/reports/{savedReportId}",
                  "httpMethod": "GET",
                  "description": "Generate an AdSense report based on the saved report ID sent in the query parameters.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "adsense.accounts.reports.saved.list",
                  "path": "accounts/{accountId}/reports/saved",
                  "httpMethod": "GET",
                  "description": "List all saved reports in the specified AdSense account.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "generate": {
              "id": "adsense.accounts.reports.generate",
              "path": "accounts/{accountId}/reports",
              "httpMethod": "GET",
              "description": "Generate an AdSense report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify \"alt=csv\" as a query parameter.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": true,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "savedadstyles": {
          "resources": {},
          "methods": {
            "get": {
              "id": "adsense.accounts.savedadstyles.get",
              "path": "accounts/{accountId}/savedadstyles/{savedAdStyleId}",
              "httpMethod": "GET",
              "description": "List a specific saved ad style for the specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "adsense.accounts.savedadstyles.list",
              "path": "accounts/{accountId}/savedadstyles",
              "httpMethod": "GET",
              "description": "List all saved ad styles in the specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "urlchannels": {
          "resources": {},
          "methods": {
            "list": {
              "id": "adsense.accounts.urlchannels.list",
              "path": "accounts/{accountId}/adclients/{adClientId}/urlchannels",
              "httpMethod": "GET",
              "description": "List all URL channels in the specified ad client for the specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "get": {
          "id": "adsense.accounts.get",
          "path": "accounts/{accountId}",
          "httpMethod": "GET",
          "description": "Get information about the selected AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "adsense.accounts.list",
          "path": "accounts",
          "httpMethod": "GET",
          "description": "List all accounts available to this AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "adclients": {
      "resources": {},
      "methods": {
        "list": {
          "id": "adsense.adclients.list",
          "path": "adclients",
          "httpMethod": "GET",
          "description": "List all ad clients in this AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "adunits": {
      "resources": {
        "customchannels": {
          "resources": {},
          "methods": {
            "list": {
              "id": "adsense.adunits.customchannels.list",
              "path": "adclients/{adClientId}/adunits/{adUnitId}/customchannels",
              "httpMethod": "GET",
              "description": "List all custom channels which the specified ad unit belongs to.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "get": {
          "id": "adsense.adunits.get",
          "path": "adclients/{adClientId}/adunits/{adUnitId}",
          "httpMethod": "GET",
          "description": "Gets the specified ad unit in the specified ad client.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "getAdCode": {
          "id": "adsense.adunits.getAdCode",
          "path": "adclients/{adClientId}/adunits/{adUnitId}/adcode",
          "httpMethod": "GET",
          "description": "Get ad code for the specified ad unit.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "adsense.adunits.list",
          "path": "adclients/{adClientId}/adunits",
          "httpMethod": "GET",
          "description": "List all ad units in the specified ad client for this AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "alerts": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "adsense.alerts.delete",
          "path": "alerts/{alertId}",
          "httpMethod": "DELETE",
          "description": "Dismiss (delete) the specified alert from the publisher's AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "adsense.alerts.list",
          "path": "alerts",
          "httpMethod": "GET",
          "description": "List the alerts for this AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "customchannels": {
      "resources": {
        "adunits": {
          "resources": {},
          "methods": {
            "list": {
              "id": "adsense.customchannels.adunits.list",
              "path": "adclients/{adClientId}/customchannels/{customChannelId}/adunits",
              "httpMethod": "GET",
              "description": "List all ad units in the specified custom channel.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "get": {
          "id": "adsense.customchannels.get",
          "path": "adclients/{adClientId}/customchannels/{customChannelId}",
          "httpMethod": "GET",
          "description": "Get the specified custom channel from the specified ad client.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "adsense.customchannels.list",
          "path": "adclients/{adClientId}/customchannels",
          "httpMethod": "GET",
          "description": "List all custom channels in the specified ad client for this AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "metadata": {
      "resources": {
        "dimensions": {
          "resources": {},
          "methods": {
            "list": {
              "id": "adsense.metadata.dimensions.list",
              "path": "metadata/dimensions",
              "httpMethod": "GET",
              "description": "List the metadata for the dimensions available to this AdSense account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "metrics": {
          "resources": {},
          "methods": {
            "list": {
              "id": "adsense.metadata.metrics.list",
              "path": "metadata/metrics",
              "httpMethod": "GET",
              "description": "List the metadata for the metrics available to this AdSense account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {}
    },
    "payments": {
      "resources": {},
      "methods": {
        "list": {
          "id": "adsense.payments.list",
          "path": "payments",
          "httpMethod": "GET",
          "description": "List the payments for this AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "reports": {
      "resources": {
        "saved": {
          "resources": {},
          "methods": {
            "generate": {
              "id": "adsense.reports.saved.generate",
              "path": "reports/{savedReportId}",
              "httpMethod": "GET",
              "description": "Generate an AdSense report based on the saved report ID sent in the query parameters.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "adsense.reports.saved.list",
              "path": "reports/saved",
              "httpMethod": "GET",
              "description": "List all saved reports in this AdSense account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "generate": {
          "id": "adsense.reports.generate",
          "path": "reports",
          "httpMethod": "GET",
          "description": "Generate an AdSense report based on the report request sent in the query parameters. Returns the result as JSON; to retrieve output in CSV format specify \"alt=csv\" as a query parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "savedadstyles": {
      "resources": {},
      "methods": {
        "get": {
          "id": "adsense.savedadstyles.get",
          "path": "savedadstyles/{savedAdStyleId}",
          "httpMethod": "GET",
          "description": "Get a specific saved ad style from the user's account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "adsense.savedadstyles.list",
          "path": "savedadstyles",
          "httpMethod": "GET",
          "description": "List all saved ad styles in the user's account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "urlchannels": {
      "resources": {},
      "methods": {
        "list": {
          "id": "adsense.urlchannels.list",
          "path": "adclients/{adClientId}/urlchannels",
          "httpMethod": "GET",
          "description": "List all URL channels in the specified ad client for this AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}