{
  "kind": "discovery#restDescription",
  "etag": null,
  "discoveryVersion": "v1",
  "id": "chromepolicy:v1",
  "name": "chromepolicy",
  "canonicalName": "Chrome Policy",
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "revision": "20210317",
  "title": "Chrome Policy API",
  "description": "The Chrome Policy API is a suite of services that allows Chrome administrators to control the policies applied to their managed Chrome OS devices and Chrome browsers.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "http://developers.google.com/chrome/policy",
  "protocol": "rest",
  "baseUrl": "https://chromepolicy.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://chromepolicy.googleapis.com/",
  "servicePath": "",
  "batchPath": "batch",
  "version_module": true,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.policy": {
          "description": "See, edit, create or delete policies applied to Chrome OS and Chrome Browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.policy.readonly": {
          "description": "See policies applied to Chrome OS and Chrome Browsers managed within your organization"
        }
      }
    }
  },
  "resources": {
    "customers": {
      "resources": {
        "policies": {
          "resources": {
            "orgunits": {
              "resources": {},
              "methods": {
                "batchInherit": {
                  "id": "chromepolicy.customers.policies.orgunits.batchInherit",
                  "path": "v1/{+customer}/policies/orgunits:batchInherit",
                  "httpMethod": "POST",
                  "description": "Modify multiple policy values that are applied to a specific org unit so that they now inherit the value from a parent (if applicable). All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`. On failure the request will return the error details as part of the google.rpc.Status.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "batchModify": {
                  "id": "chromepolicy.customers.policies.orgunits.batchModify",
                  "path": "v1/{+customer}/policies/orgunits:batchModify",
                  "httpMethod": "POST",
                  "description": "Modify multiple policy values that are applied to a specific org unit. All targets must have the same target format. That is to say that they must point to the same target resource and must have the same keys specified in `additionalTargetKeyNames`. On failure the request will return the error details as part of the google.rpc.Status.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.policy"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "resolve": {
              "id": "chromepolicy.customers.policies.resolve",
              "path": "v1/{+customer}/policies:resolve",
              "httpMethod": "POST",
              "description": "Gets the resolved policy values for a list of policies that match a search query.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "policySchemas": {
          "resources": {},
          "methods": {
            "get": {
              "id": "chromepolicy.customers.policySchemas.get",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "description": "Get a specific policy schema for a customer by its resource name.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "chromepolicy.customers.policySchemas.list",
              "path": "v1/{+parent}/policySchemas",
              "httpMethod": "GET",
              "description": "Gets a list of policy schemas that match a specified filter value for a given customer.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.policy",
                "https://www.googleapis.com/auth/chrome.management.policy.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {}
    }
  },
  "methods": {}
}