{
  "kind": "discovery#restDescription",
  "etag": "\"LYADMvHWYH2ul9D6m9UT9gT77YM/3TQy1Ai_2Z54kwW7MRlLvqd88SA\"",
  "discoveryVersion": "v1",
  "id": "fusiontables:v2",
  "name": "fusiontables",
  "canonicalName": null,
  "fullyEncodeReservedExpansion": null,
  "version": "v2",
  "revision": "20171117",
  "title": "Fusion Tables API",
  "description": "API for working with Fusion Tables data.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/fusiontables",
  "protocol": "rest",
  "baseUrl": "https://www.googleapis.com/fusiontables/v2/",
  "basePath": "/fusiontables/v2/",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "fusiontables/v2/",
  "batchPath": "batch/fusiontables/v2",
  "version_module": null,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/fusiontables": {
          "description": "Manage your Fusion Tables"
        },
        "https://www.googleapis.com/auth/fusiontables.readonly": {
          "description": "View your Fusion Tables"
        }
      }
    }
  },
  "resources": {
    "column": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "fusiontables.column.delete",
          "path": "tables/{tableId}/columns/{columnId}",
          "httpMethod": "DELETE",
          "description": "Deletes the specified column.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "fusiontables.column.get",
          "path": "tables/{tableId}/columns/{columnId}",
          "httpMethod": "GET",
          "description": "Retrieves a specific column by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "fusiontables.column.insert",
          "path": "tables/{tableId}/columns",
          "httpMethod": "POST",
          "description": "Adds a new column to the table.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "fusiontables.column.list",
          "path": "tables/{tableId}/columns",
          "httpMethod": "GET",
          "description": "Retrieves a list of columns.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "fusiontables.column.patch",
          "path": "tables/{tableId}/columns/{columnId}",
          "httpMethod": "PATCH",
          "description": "Updates the name or type of an existing column. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "fusiontables.column.update",
          "path": "tables/{tableId}/columns/{columnId}",
          "httpMethod": "PUT",
          "description": "Updates the name or type of an existing column.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "query": {
      "resources": {},
      "methods": {
        "sql": {
          "id": "fusiontables.query.sql",
          "path": "query",
          "httpMethod": "POST",
          "description": "Executes a Fusion Tables SQL statement, which can be any of \n- SELECT\n- INSERT\n- UPDATE\n- DELETE\n- SHOW\n- DESCRIBE\n- CREATE statement.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": true,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "sqlGet": {
          "id": "fusiontables.query.sqlGet",
          "path": "query",
          "httpMethod": "GET",
          "description": "Executes a SQL statement which can be any of \n- SELECT\n- SHOW\n- DESCRIBE",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": true,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "style": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "fusiontables.style.delete",
          "path": "tables/{tableId}/styles/{styleId}",
          "httpMethod": "DELETE",
          "description": "Deletes a style.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "fusiontables.style.get",
          "path": "tables/{tableId}/styles/{styleId}",
          "httpMethod": "GET",
          "description": "Gets a specific style.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "fusiontables.style.insert",
          "path": "tables/{tableId}/styles",
          "httpMethod": "POST",
          "description": "Adds a new style for the table.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "fusiontables.style.list",
          "path": "tables/{tableId}/styles",
          "httpMethod": "GET",
          "description": "Retrieves a list of styles.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "fusiontables.style.patch",
          "path": "tables/{tableId}/styles/{styleId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing style. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "fusiontables.style.update",
          "path": "tables/{tableId}/styles/{styleId}",
          "httpMethod": "PUT",
          "description": "Updates an existing style.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "table": {
      "resources": {},
      "methods": {
        "copy": {
          "id": "fusiontables.table.copy",
          "path": "tables/{tableId}/copy",
          "httpMethod": "POST",
          "description": "Copies a table.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "delete": {
          "id": "fusiontables.table.delete",
          "path": "tables/{tableId}",
          "httpMethod": "DELETE",
          "description": "Deletes a table.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "fusiontables.table.get",
          "path": "tables/{tableId}",
          "httpMethod": "GET",
          "description": "Retrieves a specific table by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "importRows": {
          "id": "fusiontables.table.importRows",
          "path": "tables/{tableId}/import",
          "httpMethod": "POST",
          "description": "Imports more rows into a table.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": true
        },
        "importTable": {
          "id": "fusiontables.table.importTable",
          "path": "tables/import",
          "httpMethod": "POST",
          "description": "Imports a new table.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": true
        },
        "insert": {
          "id": "fusiontables.table.insert",
          "path": "tables",
          "httpMethod": "POST",
          "description": "Creates a new table.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "fusiontables.table.list",
          "path": "tables",
          "httpMethod": "GET",
          "description": "Retrieves a list of tables a user owns.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "fusiontables.table.patch",
          "path": "tables/{tableId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "refetchSheet": {
          "id": "fusiontables.table.refetchSheet",
          "path": "tables/{tableId}/refetch",
          "httpMethod": "POST",
          "description": "Replaces rows of the table with the rows of the spreadsheet that is first imported from. Current rows remain visible until all replacement rows are ready.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "replaceRows": {
          "id": "fusiontables.table.replaceRows",
          "path": "tables/{tableId}/replace",
          "httpMethod": "POST",
          "description": "Replaces rows of an existing table. Current rows remain visible until all replacement rows are ready.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": true
        },
        "update": {
          "id": "fusiontables.table.update",
          "path": "tables/{tableId}",
          "httpMethod": "PUT",
          "description": "Updates an existing table. Unless explicitly requested, only the name, description, and attribution will be updated.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "task": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "fusiontables.task.delete",
          "path": "tables/{tableId}/tasks/{taskId}",
          "httpMethod": "DELETE",
          "description": "Deletes a specific task by its ID, unless that task has already started running.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "fusiontables.task.get",
          "path": "tables/{tableId}/tasks/{taskId}",
          "httpMethod": "GET",
          "description": "Retrieves a specific task by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "fusiontables.task.list",
          "path": "tables/{tableId}/tasks",
          "httpMethod": "GET",
          "description": "Retrieves a list of tasks.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "template": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "fusiontables.template.delete",
          "path": "tables/{tableId}/templates/{templateId}",
          "httpMethod": "DELETE",
          "description": "Deletes a template",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "fusiontables.template.get",
          "path": "tables/{tableId}/templates/{templateId}",
          "httpMethod": "GET",
          "description": "Retrieves a specific template by its id",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "fusiontables.template.insert",
          "path": "tables/{tableId}/templates",
          "httpMethod": "POST",
          "description": "Creates a new template for the table.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "fusiontables.template.list",
          "path": "tables/{tableId}/templates",
          "httpMethod": "GET",
          "description": "Retrieves a list of templates.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables",
            "https://www.googleapis.com/auth/fusiontables.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "fusiontables.template.patch",
          "path": "tables/{tableId}/templates/{templateId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing template. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "fusiontables.template.update",
          "path": "tables/{tableId}/templates/{templateId}",
          "httpMethod": "PUT",
          "description": "Updates an existing template",
          "scopes": [
            "https://www.googleapis.com/auth/fusiontables"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}