{
  "kind": "discovery#restDescription",
  "etag": null,
  "discoveryVersion": "v1",
  "id": "games:v1",
  "name": "games",
  "canonicalName": "Games",
  "fullyEncodeReservedExpansion": null,
  "version": "v1",
  "revision": "20210311",
  "title": "Google Play Game Services",
  "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/games/",
  "protocol": "rest",
  "baseUrl": "https://games.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://games.googleapis.com/",
  "servicePath": "",
  "batchPath": "batch",
  "version_module": null,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  },
  "resources": {
    "achievementDefinitions": {
      "resources": {},
      "methods": {
        "list": {
          "id": "games.achievementDefinitions.list",
          "path": "games/v1/achievements",
          "httpMethod": "GET",
          "description": "Lists all the achievement definitions for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "achievements": {
      "resources": {},
      "methods": {
        "increment": {
          "id": "games.achievements.increment",
          "path": "games/v1/achievements/{achievementId}/increment",
          "httpMethod": "POST",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "games.achievements.list",
          "path": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "reveal": {
          "id": "games.achievements.reveal",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "httpMethod": "POST",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "setStepsAtLeast": {
          "id": "games.achievements.setStepsAtLeast",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "httpMethod": "POST",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "unlock": {
          "id": "games.achievements.unlock",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "updateMultiple": {
          "id": "games.achievements.updateMultiple",
          "path": "games/v1/achievements/updateMultiple",
          "httpMethod": "POST",
          "description": "Updates multiple achievements for the currently authenticated player.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "applications": {
      "resources": {},
      "methods": {
        "get": {
          "id": "games.applications.get",
          "path": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "getEndPoint": {
          "id": "games.applications.getEndPoint",
          "path": "games/v1/applications/getEndPoint",
          "httpMethod": "POST",
          "description": "Returns a URL for the requested end point type.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "played": {
          "id": "games.applications.played",
          "path": "games/v1/applications/played",
          "httpMethod": "POST",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "verify": {
          "id": "games.applications.verify",
          "path": "games/v1/applications/{applicationId}/verify",
          "httpMethod": "GET",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "events": {
      "resources": {},
      "methods": {
        "listByPlayer": {
          "id": "games.events.listByPlayer",
          "path": "games/v1/events",
          "httpMethod": "GET",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "path": "games/v1/eventDefinitions",
          "httpMethod": "GET",
          "description": "Returns a list of the event definitions in this application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "record": {
          "id": "games.events.record",
          "path": "games/v1/events",
          "httpMethod": "POST",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "leaderboards": {
      "resources": {},
      "methods": {
        "get": {
          "id": "games.leaderboards.get",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "httpMethod": "GET",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "games.leaderboards.list",
          "path": "games/v1/leaderboards",
          "httpMethod": "GET",
          "description": "Lists all the leaderboard metadata for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "metagame": {
      "resources": {},
      "methods": {
        "getMetagameConfig": {
          "id": "games.metagame.getMetagameConfig",
          "path": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "description": "Return the metagame configuration data for the calling application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "listCategoriesByPlayer": {
          "id": "games.metagame.listCategoriesByPlayer",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "httpMethod": "GET",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "players": {
      "resources": {},
      "methods": {
        "get": {
          "id": "games.players.get",
          "path": "games/v1/players/{playerId}",
          "httpMethod": "GET",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "games.players.list",
          "path": "games/v1/players/me/players/{collection}",
          "httpMethod": "GET",
          "description": "Get the collection of players for the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "revisions": {
      "resources": {},
      "methods": {
        "check": {
          "id": "games.revisions.check",
          "path": "games/v1/revisions/check",
          "httpMethod": "GET",
          "description": "Checks whether the games client is out of date.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "scores": {
      "resources": {},
      "methods": {
        "get": {
          "id": "games.scores.get",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "httpMethod": "GET",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "games.scores.list",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "listWindow": {
          "id": "games.scores.listWindow",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "httpMethod": "GET",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "submit": {
          "id": "games.scores.submit",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST",
          "description": "Submits a score to the specified leaderboard.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "submitMultiple": {
          "id": "games.scores.submitMultiple",
          "path": "games/v1/leaderboards/scores",
          "httpMethod": "POST",
          "description": "Submits multiple scores to leaderboards.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "snapshots": {
      "resources": {},
      "methods": {
        "get": {
          "id": "games.snapshots.get",
          "path": "games/v1/snapshots/{snapshotId}",
          "httpMethod": "GET",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "games.snapshots.list",
          "path": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "snapshotsExtended": {
      "resources": {},
      "methods": {
        "resolveSnapshotHead": {
          "id": "games.snapshotsExtended.resolveSnapshotHead",
          "path": "games/v1/snapshotsExtended/{snapshotName}:resolveHead",
          "httpMethod": "POST",
          "description": "Resolves any potential conflicts according to the resolution policy specified in the request and returns the snapshot head after the resolution.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "stats": {
      "resources": {},
      "methods": {
        "get": {
          "id": "games.stats.get",
          "path": "games/v1/stats",
          "httpMethod": "GET",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}