{
  "kind": "discovery#restDescription",
  "etag": null,
  "discoveryVersion": "v1",
  "id": "displayvideo:v1",
  "name": "displayvideo",
  "canonicalName": "Display Video",
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "revision": "20210308",
  "title": "Display & Video 360 API",
  "description": "Display & Video 360 API allows users to manage and create campaigns and reports.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/display-video/",
  "protocol": "rest",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "servicePath": "",
  "batchPath": "batch",
  "version_module": true,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  },
  "resources": {
    "advertisers": {
      "resources": {
        "assets": {
          "resources": {},
          "methods": {
            "upload": {
              "id": "displayvideo.advertisers.assets.upload",
              "path": "v1/advertisers/{+advertiserId}/assets",
              "httpMethod": "POST",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": true
            }
          }
        },
        "campaigns": {
          "resources": {},
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.campaigns.create",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "httpMethod": "POST",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "displayvideo.advertisers.campaigns.delete",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "DELETE",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.advertisers.campaigns.get",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "GET",
              "description": "Gets a campaign.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.advertisers.campaigns.list",
              "path": "v1/advertisers/{+advertiserId}/campaigns",
              "httpMethod": "GET",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.advertisers.campaigns.patch",
              "path": "v1/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "resources": {},
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "create": {
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "delete": {
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "path": "v1/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.channels.create",
              "path": "v1/advertisers/{+advertiserId}/channels",
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.advertisers.channels.get",
              "path": "v1/advertisers/{+advertiserId}/channels/{+channelId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.advertisers.channels.list",
              "path": "v1/advertisers/{+advertiserId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.advertisers.channels.patch",
              "path": "v1/advertisers/{+advertiserId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "creatives": {
          "resources": {},
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.creatives.create",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "httpMethod": "POST",
              "description": "Creates a new creative. Returns the newly created creative if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "displayvideo.advertisers.creatives.delete",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "DELETE",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.advertisers.creatives.get",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.advertisers.creatives.list",
              "path": "v1/advertisers/{+advertiserId}/creatives",
              "httpMethod": "GET",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.advertisers.creatives.patch",
              "path": "v1/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing creative. Returns the updated creative if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "insertionOrders": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "resources": {},
                  "methods": {
                    "get": {
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.get",
                      "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to an insertion order.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "displayvideo.advertisers.insertionOrders.targetingTypes.assignedTargetingOptions.list",
                      "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to an insertion order.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                }
              },
              "methods": {}
            }
          },
          "methods": {
            "bulkListInsertionOrderAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.insertionOrders.bulkListInsertionOrderAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}:bulkListInsertionOrderAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options of an insertion order across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "create": {
              "id": "displayvideo.advertisers.insertionOrders.create",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "httpMethod": "POST",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "DELETE",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.advertisers.insertionOrders.get",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "GET",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.advertisers.insertionOrders.list",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders",
              "httpMethod": "GET",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "path": "v1/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "lineItems": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "resources": {},
                  "methods": {
                    "create": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "get": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                }
              },
              "methods": {}
            }
          },
          "methods": {
            "bulkEditLineItemAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkEditLineItemAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkEditLineItemAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options under a single line item. The operation will delete the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditLineItemAssignedTargetingOptionsRequest.create_requests .",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "bulkListLineItemAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkListLineItemAssignedTargetingOptions",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}:bulkListLineItemAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options of a line item across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "create": {
              "id": "displayvideo.advertisers.lineItems.create",
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "POST",
              "description": "Creates a new line item. Returns the newly created line item if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "displayvideo.advertisers.lineItems.delete",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.advertisers.lineItems.get",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "GET",
              "description": "Gets a line item.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.advertisers.lineItems.list",
              "path": "v1/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "GET",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.advertisers.lineItems.patch",
              "path": "v1/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing line item. Returns the updated line item if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "locationLists": {
          "resources": {
            "assignedLocations": {
              "resources": {},
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in BulkEditAssignedLocationsRequest.deleted_assigned_locations and then create the assigned locations provided in BulkEditAssignedLocationsRequest.created_assigned_locations.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "create": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "description": "Creates an assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "delete": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes the assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "path": "v1/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "description": "Lists locations assigned to a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.advertisers.locationLists.get",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "httpMethod": "GET",
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.advertisers.locationLists.list",
              "path": "v1/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "GET",
              "description": "Lists location lists based on a given advertiser id.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.advertisers.locationLists.patch",
              "path": "v1/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "manualTriggers": {
          "resources": {},
          "methods": {
            "activate": {
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "httpMethod": "POST",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "create": {
              "id": "displayvideo.advertisers.manualTriggers.create",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "httpMethod": "POST",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "deactivate": {
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "httpMethod": "POST",
              "description": "Deactivates a manual trigger.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.advertisers.manualTriggers.get",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "httpMethod": "GET",
              "description": "Gets a manual trigger.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.advertisers.manualTriggers.list",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers",
              "httpMethod": "GET",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "path": "v1/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "httpMethod": "PATCH",
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "negativeKeywordLists": {
          "resources": {
            "negativeKeywords": {
              "resources": {},
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "create": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "httpMethod": "POST",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "delete": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "path": "v1/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "httpMethod": "GET",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "httpMethod": "DELETE",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "GET",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "path": "v1/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "resources": {},
              "methods": {
                "create": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "delete": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "get": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "path": "v1/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {}
        }
      },
      "methods": {
        "audit": {
          "id": "displayvideo.advertisers.audit",
          "path": "v1/advertisers/{+advertiserId}:audit",
          "httpMethod": "GET",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "bulkEditAdvertiserAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.bulkEditAdvertiserAssignedTargetingOptions",
          "path": "v1/advertisers/{+advertiserId}:bulkEditAdvertiserAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Bulk edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "bulkListAdvertiserAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.bulkListAdvertiserAssignedTargetingOptions",
          "path": "v1/advertisers/{+advertiserId}:bulkListAdvertiserAssignedTargetingOptions",
          "httpMethod": "GET",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "create": {
          "id": "displayvideo.advertisers.create",
          "path": "v1/advertisers",
          "httpMethod": "POST",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. This method can take up to 180 seconds to complete.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "delete": {
          "id": "displayvideo.advertisers.delete",
          "path": "v1/advertisers/{+advertiserId}",
          "httpMethod": "DELETE",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "displayvideo.advertisers.get",
          "path": "v1/advertisers/{+advertiserId}",
          "httpMethod": "GET",
          "description": "Gets an advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.advertisers.list",
          "path": "v1/advertisers",
          "httpMethod": "GET",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "displayvideo.advertisers.patch",
          "path": "v1/advertisers/{+advertiserId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "combinedAudiences": {
      "resources": {},
      "methods": {
        "get": {
          "id": "displayvideo.combinedAudiences.get",
          "path": "v1/combinedAudiences/{+combinedAudienceId}",
          "httpMethod": "GET",
          "description": "Gets a combined audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.combinedAudiences.list",
          "path": "v1/combinedAudiences",
          "httpMethod": "GET",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "customBiddingAlgorithms": {
      "resources": {},
      "methods": {
        "get": {
          "id": "displayvideo.customBiddingAlgorithms.get",
          "path": "v1/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "httpMethod": "GET",
          "description": "Gets a custom bidding algorithm.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.customBiddingAlgorithms.list",
          "path": "v1/customBiddingAlgorithms",
          "httpMethod": "GET",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "customLists": {
      "resources": {},
      "methods": {
        "get": {
          "id": "displayvideo.customLists.get",
          "path": "v1/customLists/{+customListId}",
          "httpMethod": "GET",
          "description": "Gets a custom list.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.customLists.list",
          "path": "v1/customLists",
          "httpMethod": "GET",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "resources": {},
      "methods": {
        "get": {
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "path": "v1/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "httpMethod": "GET",
          "description": "Gets a first and third party audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "path": "v1/firstAndThirdPartyAudiences",
          "httpMethod": "GET",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "floodlightGroups": {
      "resources": {},
      "methods": {
        "get": {
          "id": "displayvideo.floodlightGroups.get",
          "path": "v1/floodlightGroups/{+floodlightGroupId}",
          "httpMethod": "GET",
          "description": "Gets a Floodlight group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v1/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "googleAudiences": {
      "resources": {},
      "methods": {
        "get": {
          "id": "displayvideo.googleAudiences.get",
          "path": "v1/googleAudiences/{+googleAudienceId}",
          "httpMethod": "GET",
          "description": "Gets a Google audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.googleAudiences.list",
          "path": "v1/googleAudiences",
          "httpMethod": "GET",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "inventorySourceGroups": {
      "resources": {
        "assignedInventorySources": {
          "resources": {},
          "methods": {
            "bulkEdit": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "create": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "POST",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "httpMethod": "DELETE",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "GET",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "create": {
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v1/inventorySourceGroups",
          "httpMethod": "POST",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "delete": {
          "id": "displayvideo.inventorySourceGroups.delete",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "httpMethod": "DELETE",
          "description": "Deletes an inventory source group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "displayvideo.inventorySourceGroups.get",
          "path": "v1/inventorySourceGroups/{+inventorySourceGroupId}",
          "httpMethod": "GET",
          "description": "Gets an inventory source group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.inventorySourceGroups.list",
          "path": "v1/inventorySourceGroups",
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "displayvideo.inventorySourceGroups.patch",
          "path": "v1/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "inventorySources": {
      "resources": {},
      "methods": {
        "get": {
          "id": "displayvideo.inventorySources.get",
          "path": "v1/inventorySources/{+inventorySourceId}",
          "httpMethod": "GET",
          "description": "Gets an inventory source.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.inventorySources.list",
          "path": "v1/inventorySources",
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "media": {
      "resources": {},
      "methods": {
        "download": {
          "id": "displayvideo.media.download",
          "path": "download/{+resourceName}",
          "httpMethod": "GET",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "partners": {
      "resources": {
        "channels": {
          "resources": {
            "sites": {
              "resources": {},
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "create": {
                  "id": "displayvideo.partners.channels.sites.create",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "delete": {
                  "id": "displayvideo.partners.channels.sites.delete",
                  "path": "v1/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "displayvideo.partners.channels.sites.list",
                  "path": "v1/partners/{+partnerId}/channels/{+channelId}/sites",
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "create": {
              "id": "displayvideo.partners.channels.create",
              "path": "v1/partners/{+partnerId}/channels",
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "displayvideo.partners.channels.get",
              "path": "v1/partners/{+partnerId}/channels/{+channelId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.partners.channels.list",
              "path": "v1/partners/{+partnerId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "displayvideo.partners.channels.patch",
              "path": "v1/partners/{+partnerId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "resources": {},
              "methods": {
                "create": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "delete": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "get": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "path": "v1/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {}
        }
      },
      "methods": {
        "bulkEditPartnerAssignedTargetingOptions": {
          "id": "displayvideo.partners.bulkEditPartnerAssignedTargetingOptions",
          "path": "v1/partners/{+partnerId}:bulkEditPartnerAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Bulk edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "displayvideo.partners.get",
          "path": "v1/partners/{+partnerId}",
          "httpMethod": "GET",
          "description": "Gets a partner.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.partners.list",
          "path": "v1/partners",
          "httpMethod": "GET",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "sdfdownloadtasks": {
      "resources": {
        "operations": {
          "resources": {},
          "methods": {
            "get": {
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "create": {
          "id": "displayvideo.sdfdownloadtasks.create",
          "path": "v1/sdfdownloadtasks",
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with sdfdownloadtask.operations.get. Any errors can be found in the error.[...]",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "resources": {},
          "methods": {
            "get": {
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "httpMethod": "GET",
              "description": "Gets a single targeting option.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions",
              "httpMethod": "GET",
              "description": "Lists targeting options of a given type.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "search": {
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "path": "v1/targetingTypes/{+targetingType}/targetingOptions:search",
              "httpMethod": "POST",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {}
    },
    "users": {
      "resources": {},
      "methods": {
        "bulkEditAssignedUserRoles": {
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "path": "v1/users/{+userId}:bulkEditAssignedUserRoles",
          "httpMethod": "POST",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "create": {
          "id": "displayvideo.users.create",
          "path": "v1/users",
          "httpMethod": "POST",
          "description": "Creates a new user. Returns the newly created user if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "delete": {
          "id": "displayvideo.users.delete",
          "path": "v1/users/{+userId}",
          "httpMethod": "DELETE",
          "description": "Deletes a user.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "displayvideo.users.get",
          "path": "v1/users/{+userId}",
          "httpMethod": "GET",
          "description": "Gets a user.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "displayvideo.users.list",
          "path": "v1/users",
          "httpMethod": "GET",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "displayvideo.users.patch",
          "path": "v1/users/{+userId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing user. Returns the updated user if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}