{
  "kind": "discovery#restDescription",
  "etag": "\"9eZ1uxVRThTDhLJCZHhqs3eQWz4/-TzTVsRsi4n00x2wApWXGdbgjmQ\"",
  "discoveryVersion": "v1",
  "id": "replicapool:v1beta1",
  "name": "replicapool",
  "canonicalName": null,
  "fullyEncodeReservedExpansion": null,
  "version": "v1beta1",
  "revision": "20160512",
  "title": "Replica Pool API",
  "description": "The Replica Pool API allows users to declaratively provision and manage groups of Google Compute Engine instances based on a common template.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/compute/docs/replica-pool/",
  "protocol": "rest",
  "baseUrl": "https://www.googleapis.com/replicapool/v1beta1/projects/",
  "basePath": "/replicapool/v1beta1/projects/",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "replicapool/v1beta1/projects/",
  "batchPath": "batch/replicapool/v1beta1",
  "version_module": null,
  "packagePath": null,
  "labels": [
    "limited_availability"
  ],
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud Platform services"
        },
        "https://www.googleapis.com/auth/ndev.cloudman": {
          "description": "View and manage your Google Cloud Platform management resources and deployment status information"
        },
        "https://www.googleapis.com/auth/ndev.cloudman.readonly": {
          "description": "View your Google Cloud Platform management resources and deployment status information"
        },
        "https://www.googleapis.com/auth/replicapool": {
          "description": "View and manage replica pools"
        },
        "https://www.googleapis.com/auth/replicapool.readonly": {
          "description": "View replica pools"
        }
      }
    }
  },
  "resources": {
    "pools": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "replicapool.pools.delete",
          "path": "{projectName}/zones/{zone}/pools/{poolName}",
          "httpMethod": "POST",
          "description": "Deletes a replica pool.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/replicapool"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "replicapool.pools.get",
          "path": "{projectName}/zones/{zone}/pools/{poolName}",
          "httpMethod": "GET",
          "description": "Gets information about a single replica pool.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/ndev.cloudman.readonly",
            "https://www.googleapis.com/auth/replicapool",
            "https://www.googleapis.com/auth/replicapool.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "replicapool.pools.insert",
          "path": "{projectName}/zones/{zone}/pools",
          "httpMethod": "POST",
          "description": "Inserts a new replica pool.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/replicapool"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "replicapool.pools.list",
          "path": "{projectName}/zones/{zone}/pools",
          "httpMethod": "GET",
          "description": "List all replica pools.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/ndev.cloudman.readonly",
            "https://www.googleapis.com/auth/replicapool",
            "https://www.googleapis.com/auth/replicapool.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "resize": {
          "id": "replicapool.pools.resize",
          "path": "{projectName}/zones/{zone}/pools/{poolName}/resize",
          "httpMethod": "POST",
          "description": "Resize a pool. This is an asynchronous operation, and multiple overlapping resize requests can be made. Replica Pools will use the information from the last resize request.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/replicapool"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "updatetemplate": {
          "id": "replicapool.pools.updatetemplate",
          "path": "{projectName}/zones/{zone}/pools/{poolName}/updateTemplate",
          "httpMethod": "POST",
          "description": "Update the template used by the pool.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/replicapool"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "replicas": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "replicapool.replicas.delete",
          "path": "{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}",
          "httpMethod": "POST",
          "description": "Deletes a replica from the pool.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/replicapool"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "replicapool.replicas.get",
          "path": "{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}",
          "httpMethod": "GET",
          "description": "Gets information about a specific replica.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/ndev.cloudman.readonly",
            "https://www.googleapis.com/auth/replicapool",
            "https://www.googleapis.com/auth/replicapool.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "replicapool.replicas.list",
          "path": "{projectName}/zones/{zone}/pools/{poolName}/replicas",
          "httpMethod": "GET",
          "description": "Lists all replicas in a pool.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/ndev.cloudman.readonly",
            "https://www.googleapis.com/auth/replicapool",
            "https://www.googleapis.com/auth/replicapool.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "restart": {
          "id": "replicapool.replicas.restart",
          "path": "{projectName}/zones/{zone}/pools/{poolName}/replicas/{replicaName}/restart",
          "httpMethod": "POST",
          "description": "Restarts a replica in a pool.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/ndev.cloudman",
            "https://www.googleapis.com/auth/replicapool"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}