{
  "kind": "discovery#restDescription",
  "etag": null,
  "discoveryVersion": "v1",
  "id": "docs:v1",
  "name": "docs",
  "canonicalName": "Docs",
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "revision": "20210302",
  "title": "Google Docs API",
  "description": "Reads and writes Google Docs documents.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/docs/",
  "protocol": "rest",
  "baseUrl": "https://docs.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://docs.googleapis.com/",
  "servicePath": "",
  "batchPath": "batch",
  "version_module": true,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/documents": {
          "description": "See, create, and edit all Google Docs documents you have access to"
        },
        "https://www.googleapis.com/auth/documents.readonly": {
          "description": "View your Google Docs documents"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        }
      }
    }
  },
  "resources": {
    "documents": {
      "resources": {},
      "methods": {
        "batchUpdate": {
          "id": "docs.documents.batchUpdate",
          "path": "v1/documents/{documentId}:batchUpdate",
          "httpMethod": "POST",
          "description": "Applies one or more updates to the document. Each request is validated before being applied. If any request is not valid, then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. Other requests do not need to return information; these each return an empty reply. The order of replies matches that of the requests. For example, suppose you call batchUpdate with four updates, and only [...]",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "create": {
          "id": "docs.documents.create",
          "path": "v1/documents",
          "httpMethod": "POST",
          "description": "Creates a blank document using the title given in the request. Other fields in the request, including any provided content, are ignored. Returns the created document.",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "docs.documents.get",
          "path": "v1/documents/{documentId}",
          "httpMethod": "GET",
          "description": "Gets the latest version of the specified document.",
          "scopes": [
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/documents.readonly",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}