{
  "kind": "discovery#restDescription",
  "etag": "\"9eZ1uxVRThTDhLJCZHhqs3eQWz4/Or-xZvCZIz5Paj-rr5c5BzwXAYo\"",
  "discoveryVersion": "v1",
  "id": "surveys:v2",
  "name": "surveys",
  "canonicalName": "Surveys",
  "fullyEncodeReservedExpansion": null,
  "version": "v2",
  "revision": "20180508",
  "title": "Surveys API",
  "description": "Creates and conducts surveys, lists the surveys that an authenticated user owns, and retrieves survey results and information about specified surveys.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": null,
  "protocol": "rest",
  "baseUrl": "https://www.googleapis.com/surveys/v2/",
  "basePath": "/surveys/v2/",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "surveys/v2/",
  "batchPath": "batch/surveys/v2",
  "version_module": null,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/surveys": {
          "description": "View and manage your surveys and results"
        },
        "https://www.googleapis.com/auth/surveys.readonly": {
          "description": "View your surveys and survey results"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        }
      }
    }
  },
  "resources": {
    "results": {
      "resources": {},
      "methods": {
        "get": {
          "id": "surveys.results.get",
          "path": "surveys/{surveyUrlId}/results",
          "httpMethod": "GET",
          "description": "Retrieves any survey results that have been produced so far. Results are formatted as an Excel file. You must add \"?alt=media\" to the URL as an argument to get results.",
          "scopes": [
            "https://www.googleapis.com/auth/surveys",
            "https://www.googleapis.com/auth/surveys.readonly",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "surveys": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "surveys.surveys.delete",
          "path": "surveys/{surveyUrlId}",
          "httpMethod": "DELETE",
          "description": "Removes a survey from view in all user GET requests.",
          "scopes": [
            "https://www.googleapis.com/auth/surveys",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "surveys.surveys.get",
          "path": "surveys/{surveyUrlId}",
          "httpMethod": "GET",
          "description": "Retrieves information about the specified survey.",
          "scopes": [
            "https://www.googleapis.com/auth/surveys",
            "https://www.googleapis.com/auth/surveys.readonly",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "surveys.surveys.insert",
          "path": "surveys",
          "httpMethod": "POST",
          "description": "Creates a survey.",
          "scopes": [
            "https://www.googleapis.com/auth/surveys",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "surveys.surveys.list",
          "path": "surveys",
          "httpMethod": "GET",
          "description": "Lists the surveys owned by the authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/surveys",
            "https://www.googleapis.com/auth/surveys.readonly",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "start": {
          "id": "surveys.surveys.start",
          "path": "surveys/{resourceId}/start",
          "httpMethod": "POST",
          "description": "Begins running a survey.",
          "scopes": [
            "https://www.googleapis.com/auth/surveys",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "stop": {
          "id": "surveys.surveys.stop",
          "path": "surveys/{resourceId}/stop",
          "httpMethod": "POST",
          "description": "Stops a running survey.",
          "scopes": [
            "https://www.googleapis.com/auth/surveys",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "surveys.surveys.update",
          "path": "surveys/{surveyUrlId}",
          "httpMethod": "PUT",
          "description": "Updates a survey. Currently the only property that can be updated is the owners property.",
          "scopes": [
            "https://www.googleapis.com/auth/surveys",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}