{
  "kind": "discovery#restDescription",
  "etag": "\"9eZ1uxVRThTDhLJCZHhqs3eQWz4/DTmHY5YcSH4XeouavtxWfeZiT6M\"",
  "discoveryVersion": "v1",
  "id": "tagmanager:v2",
  "name": "tagmanager",
  "canonicalName": "Tag Manager",
  "fullyEncodeReservedExpansion": null,
  "version": "v2",
  "revision": "20190516",
  "title": "Tag Manager API",
  "description": "Accesses Tag Manager accounts and containers.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/tag-manager/api/v2/",
  "protocol": "rest",
  "baseUrl": "https://www.googleapis.com/tagmanager/v2/",
  "basePath": "/tagmanager/v2/",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "tagmanager/v2/",
  "batchPath": "batch/tagmanager/v2",
  "version_module": null,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/tagmanager.delete.containers": {
          "description": "Delete your Google Tag Manager containers"
        },
        "https://www.googleapis.com/auth/tagmanager.edit.containers": {
          "description": "Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing"
        },
        "https://www.googleapis.com/auth/tagmanager.edit.containerversions": {
          "description": "Manage your Google Tag Manager container versions"
        },
        "https://www.googleapis.com/auth/tagmanager.manage.accounts": {
          "description": "View and manage your Google Tag Manager accounts"
        },
        "https://www.googleapis.com/auth/tagmanager.manage.users": {
          "description": "Manage user permissions of your Google Tag Manager account and container"
        },
        "https://www.googleapis.com/auth/tagmanager.publish": {
          "description": "Publish your Google Tag Manager container versions"
        },
        "https://www.googleapis.com/auth/tagmanager.readonly": {
          "description": "View your Google Tag Manager container and its subcomponents"
        }
      }
    }
  },
  "resources": {
    "accounts": {
      "resources": {
        "containers": {
          "resources": {
            "environments": {
              "resources": {},
              "methods": {
                "create": {
                  "id": "tagmanager.accounts.containers.environments.create",
                  "path": "{+parent}/environments",
                  "httpMethod": "POST",
                  "description": "Creates a GTM Environment.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "delete": {
                  "id": "tagmanager.accounts.containers.environments.delete",
                  "path": "{+path}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a GTM Environment.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "get": {
                  "id": "tagmanager.accounts.containers.environments.get",
                  "path": "{+path}",
                  "httpMethod": "GET",
                  "description": "Gets a GTM Environment.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "tagmanager.accounts.containers.environments.list",
                  "path": "{+parent}/environments",
                  "httpMethod": "GET",
                  "description": "Lists all GTM Environments of a GTM Container.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "reauthorize": {
                  "id": "tagmanager.accounts.containers.environments.reauthorize",
                  "path": "{+path}:reauthorize",
                  "httpMethod": "POST",
                  "description": "Re-generates the authorization code for a GTM Environment.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.publish"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "update": {
                  "id": "tagmanager.accounts.containers.environments.update",
                  "path": "{+path}",
                  "httpMethod": "PUT",
                  "description": "Updates a GTM Environment.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            },
            "version_headers": {
              "resources": {},
              "methods": {
                "latest": {
                  "id": "tagmanager.accounts.containers.version_headers.latest",
                  "path": "{+parent}/version_headers:latest",
                  "httpMethod": "GET",
                  "description": "Gets the latest container version header",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "tagmanager.accounts.containers.version_headers.list",
                  "path": "{+parent}/version_headers",
                  "httpMethod": "GET",
                  "description": "Lists all Container Versions of a GTM Container.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            },
            "versions": {
              "resources": {},
              "methods": {
                "delete": {
                  "id": "tagmanager.accounts.containers.versions.delete",
                  "path": "{+path}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a Container Version.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "get": {
                  "id": "tagmanager.accounts.containers.versions.get",
                  "path": "{+path}",
                  "httpMethod": "GET",
                  "description": "Gets a Container Version.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "live": {
                  "id": "tagmanager.accounts.containers.versions.live",
                  "path": "{+parent}/versions:live",
                  "httpMethod": "GET",
                  "description": "Gets the live (i.e. published) container version",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "publish": {
                  "id": "tagmanager.accounts.containers.versions.publish",
                  "path": "{+path}:publish",
                  "httpMethod": "POST",
                  "description": "Publishes a Container Version.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.publish"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "set_latest": {
                  "id": "tagmanager.accounts.containers.versions.set_latest",
                  "path": "{+path}:set_latest",
                  "httpMethod": "POST",
                  "description": "Sets the latest version used for synchronization of workspaces when detecting conflicts and errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "undelete": {
                  "id": "tagmanager.accounts.containers.versions.undelete",
                  "path": "{+path}:undelete",
                  "httpMethod": "POST",
                  "description": "Undeletes a Container Version.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "update": {
                  "id": "tagmanager.accounts.containers.versions.update",
                  "path": "{+path}",
                  "httpMethod": "PUT",
                  "description": "Updates a Container Version.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            },
            "workspaces": {
              "resources": {
                "built_in_variables": {
                  "resources": {},
                  "methods": {
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.create",
                      "path": "{+parent}/built_in_variables",
                      "httpMethod": "POST",
                      "description": "Creates one or more GTM Built-In Variables.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "delete": {
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.delete",
                      "path": "{+path}",
                      "httpMethod": "DELETE",
                      "description": "Deletes one or more GTM Built-In Variables.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.list",
                      "path": "{+parent}/built_in_variables",
                      "httpMethod": "GET",
                      "description": "Lists all the enabled Built-In Variables of a GTM Container.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.revert",
                      "path": "{+path}/built_in_variables:revert",
                      "httpMethod": "POST",
                      "description": "Reverts changes to a GTM Built-In Variables in a GTM Workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                },
                "folders": {
                  "resources": {},
                  "methods": {
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.create",
                      "path": "{+parent}/folders",
                      "httpMethod": "POST",
                      "description": "Creates a GTM Folder.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "delete": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.delete",
                      "path": "{+path}",
                      "httpMethod": "DELETE",
                      "description": "Deletes a GTM Folder.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "entities": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.entities",
                      "path": "{+path}:entities",
                      "httpMethod": "POST",
                      "description": "List all entities in a GTM Folder.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.get",
                      "path": "{+path}",
                      "httpMethod": "GET",
                      "description": "Gets a GTM Folder.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.list",
                      "path": "{+parent}/folders",
                      "httpMethod": "GET",
                      "description": "Lists all GTM Folders of a Container.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "move_entities_to_folder": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.move_entities_to_folder",
                      "path": "{+path}:move_entities_to_folder",
                      "httpMethod": "POST",
                      "description": "Moves entities to a GTM Folder.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.revert",
                      "path": "{+path}:revert",
                      "httpMethod": "POST",
                      "description": "Reverts changes to a GTM Folder in a GTM Workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.update",
                      "path": "{+path}",
                      "httpMethod": "PUT",
                      "description": "Updates a GTM Folder.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                },
                "tags": {
                  "resources": {},
                  "methods": {
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.create",
                      "path": "{+parent}/tags",
                      "httpMethod": "POST",
                      "description": "Creates a GTM Tag.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "delete": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.delete",
                      "path": "{+path}",
                      "httpMethod": "DELETE",
                      "description": "Deletes a GTM Tag.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.get",
                      "path": "{+path}",
                      "httpMethod": "GET",
                      "description": "Gets a GTM Tag.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.list",
                      "path": "{+parent}/tags",
                      "httpMethod": "GET",
                      "description": "Lists all GTM Tags of a Container.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.revert",
                      "path": "{+path}:revert",
                      "httpMethod": "POST",
                      "description": "Reverts changes to a GTM Tag in a GTM Workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.update",
                      "path": "{+path}",
                      "httpMethod": "PUT",
                      "description": "Updates a GTM Tag.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                },
                "templates": {
                  "resources": {},
                  "methods": {
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.create",
                      "path": "{+parent}/templates",
                      "httpMethod": "POST",
                      "description": "Creates a GTM Custom Template.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "delete": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.delete",
                      "path": "{+path}",
                      "httpMethod": "DELETE",
                      "description": "Deletes a GTM Template.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.get",
                      "path": "{+path}",
                      "httpMethod": "GET",
                      "description": "Gets a GTM Template.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.list",
                      "path": "{+parent}/templates",
                      "httpMethod": "GET",
                      "description": "Lists all GTM Templates of a GTM container workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.revert",
                      "path": "{+path}:revert",
                      "httpMethod": "POST",
                      "description": "Reverts changes to a GTM Template in a GTM Workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.update",
                      "path": "{+path}",
                      "httpMethod": "PUT",
                      "description": "Updates a GTM Template.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                },
                "triggers": {
                  "resources": {},
                  "methods": {
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.create",
                      "path": "{+parent}/triggers",
                      "httpMethod": "POST",
                      "description": "Creates a GTM Trigger.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "delete": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.delete",
                      "path": "{+path}",
                      "httpMethod": "DELETE",
                      "description": "Deletes a GTM Trigger.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.get",
                      "path": "{+path}",
                      "httpMethod": "GET",
                      "description": "Gets a GTM Trigger.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.list",
                      "path": "{+parent}/triggers",
                      "httpMethod": "GET",
                      "description": "Lists all GTM Triggers of a Container.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.revert",
                      "path": "{+path}:revert",
                      "httpMethod": "POST",
                      "description": "Reverts changes to a GTM Trigger in a GTM Workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.update",
                      "path": "{+path}",
                      "httpMethod": "PUT",
                      "description": "Updates a GTM Trigger.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                },
                "variables": {
                  "resources": {},
                  "methods": {
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.create",
                      "path": "{+parent}/variables",
                      "httpMethod": "POST",
                      "description": "Creates a GTM Variable.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "delete": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.delete",
                      "path": "{+path}",
                      "httpMethod": "DELETE",
                      "description": "Deletes a GTM Variable.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.get",
                      "path": "{+path}",
                      "httpMethod": "GET",
                      "description": "Gets a GTM Variable.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.list",
                      "path": "{+parent}/variables",
                      "httpMethod": "GET",
                      "description": "Lists all GTM Variables of a Container.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.revert",
                      "path": "{+path}:revert",
                      "httpMethod": "POST",
                      "description": "Reverts changes to a GTM Variable in a GTM Workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.update",
                      "path": "{+path}",
                      "httpMethod": "PUT",
                      "description": "Updates a GTM Variable.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                },
                "zones": {
                  "resources": {},
                  "methods": {
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.zones.create",
                      "path": "{+parent}/zones",
                      "httpMethod": "POST",
                      "description": "Creates a GTM Zone.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "delete": {
                      "id": "tagmanager.accounts.containers.workspaces.zones.delete",
                      "path": "{+path}",
                      "httpMethod": "DELETE",
                      "description": "Deletes a GTM Zone.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.zones.get",
                      "path": "{+path}",
                      "httpMethod": "GET",
                      "description": "Gets a GTM Zone.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.zones.list",
                      "path": "{+parent}/zones",
                      "httpMethod": "GET",
                      "description": "Lists all GTM Zones of a GTM container workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.zones.revert",
                      "path": "{+path}:revert",
                      "httpMethod": "POST",
                      "description": "Reverts changes to a GTM Zone in a GTM Workspace.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.zones.update",
                      "path": "{+path}",
                      "httpMethod": "PUT",
                      "description": "Updates a GTM Zone.",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "supportsMediaDownload": false,
                      "useMediaDownloadService": false,
                      "supportsSubscription": false,
                      "supportsMediaUpload": false
                    }
                  }
                }
              },
              "methods": {
                "create": {
                  "id": "tagmanager.accounts.containers.workspaces.create",
                  "path": "{+parent}/workspaces",
                  "httpMethod": "POST",
                  "description": "Creates a Workspace.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "create_version": {
                  "id": "tagmanager.accounts.containers.workspaces.create_version",
                  "path": "{+path}:create_version",
                  "httpMethod": "POST",
                  "description": "Creates a Container Version from the entities present in the workspace, deletes the workspace, and sets the base container version to the newly created version.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "delete": {
                  "id": "tagmanager.accounts.containers.workspaces.delete",
                  "path": "{+path}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a Workspace.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.delete.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "get": {
                  "id": "tagmanager.accounts.containers.workspaces.get",
                  "path": "{+path}",
                  "httpMethod": "GET",
                  "description": "Gets a Workspace.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "getStatus": {
                  "id": "tagmanager.accounts.containers.workspaces.getStatus",
                  "path": "{+path}/status",
                  "httpMethod": "GET",
                  "description": "Finds conflicting and modified entities in the workspace.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "list": {
                  "id": "tagmanager.accounts.containers.workspaces.list",
                  "path": "{+parent}/workspaces",
                  "httpMethod": "GET",
                  "description": "Lists all Workspaces that belong to a GTM Container.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "quick_preview": {
                  "id": "tagmanager.accounts.containers.workspaces.quick_preview",
                  "path": "{+path}:quick_preview",
                  "httpMethod": "POST",
                  "description": "Quick previews a workspace by creating a fake container version from all entities in the provided workspace.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "resolve_conflict": {
                  "id": "tagmanager.accounts.containers.workspaces.resolve_conflict",
                  "path": "{+path}:resolve_conflict",
                  "httpMethod": "POST",
                  "description": "Resolves a merge conflict for a workspace entity by updating it to the resolved entity passed in the request.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "sync": {
                  "id": "tagmanager.accounts.containers.workspaces.sync",
                  "path": "{+path}:sync",
                  "httpMethod": "POST",
                  "description": "Syncs a workspace to the latest container version by updating all unmodified workspace entities and displaying conflicts for modified entities.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                },
                "update": {
                  "id": "tagmanager.accounts.containers.workspaces.update",
                  "path": "{+path}",
                  "httpMethod": "PUT",
                  "description": "Updates a Workspace.",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "supportsMediaDownload": false,
                  "useMediaDownloadService": false,
                  "supportsSubscription": false,
                  "supportsMediaUpload": false
                }
              }
            }
          },
          "methods": {
            "create": {
              "id": "tagmanager.accounts.containers.create",
              "path": "{+parent}/containers",
              "httpMethod": "POST",
              "description": "Creates a Container.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "tagmanager.accounts.containers.delete",
              "path": "{+path}",
              "httpMethod": "DELETE",
              "description": "Deletes a Container.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.delete.containers"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "tagmanager.accounts.containers.get",
              "path": "{+path}",
              "httpMethod": "GET",
              "description": "Gets a Container.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "tagmanager.accounts.containers.list",
              "path": "{+parent}/containers",
              "httpMethod": "GET",
              "description": "Lists all Containers that belongs to a GTM Account.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "update": {
              "id": "tagmanager.accounts.containers.update",
              "path": "{+path}",
              "httpMethod": "PUT",
              "description": "Updates a Container.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "user_permissions": {
          "resources": {},
          "methods": {
            "create": {
              "id": "tagmanager.accounts.user_permissions.create",
              "path": "{+parent}/user_permissions",
              "httpMethod": "POST",
              "description": "Creates a user's Account & Container access.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "tagmanager.accounts.user_permissions.delete",
              "path": "{+path}",
              "httpMethod": "DELETE",
              "description": "Removes a user from the account, revoking access to it and all of its containers.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "tagmanager.accounts.user_permissions.get",
              "path": "{+path}",
              "httpMethod": "GET",
              "description": "Gets a user's Account & Container access.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "tagmanager.accounts.user_permissions.list",
              "path": "{+parent}/user_permissions",
              "httpMethod": "GET",
              "description": "List all users that have access to the account along with Account and Container user access granted to each of them.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "update": {
              "id": "tagmanager.accounts.user_permissions.update",
              "path": "{+path}",
              "httpMethod": "PUT",
              "description": "Updates a user's Account & Container access.",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "get": {
          "id": "tagmanager.accounts.get",
          "path": "{+path}",
          "httpMethod": "GET",
          "description": "Gets a GTM Account.",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.manage.accounts",
            "https://www.googleapis.com/auth/tagmanager.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "tagmanager.accounts.list",
          "path": "accounts",
          "httpMethod": "GET",
          "description": "Lists all GTM Accounts that a user has access to.",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.manage.accounts",
            "https://www.googleapis.com/auth/tagmanager.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "tagmanager.accounts.update",
          "path": "{+path}",
          "httpMethod": "PUT",
          "description": "Updates a GTM Account.",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.manage.accounts"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}