{
  "kind": "discovery#restDescription",
  "etag": null,
  "discoveryVersion": "v1",
  "id": "dfareporting:v3.4",
  "name": "dfareporting",
  "canonicalName": "Dfareporting",
  "fullyEncodeReservedExpansion": null,
  "version": "v3.4",
  "revision": "20210210",
  "title": "Campaign Manager 360 API",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "protocol": "rest",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v3.4/",
  "basePath": "/dfareporting/v3.4/",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "servicePath": "dfareporting/v3.4/",
  "batchPath": "batch",
  "version_module": null,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "resources": {
    "accountActiveAdSummaries": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.accountActiveAdSummaries.get",
          "path": "userprofiles/{profileId}/accountActiveAdSummaries/{summaryAccountId}",
          "httpMethod": "GET",
          "description": "Gets the account's active ad summary by account ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "accountPermissionGroups": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissionGroups.get",
          "path": "userprofiles/{profileId}/accountPermissionGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.accountPermissionGroups.list",
          "path": "userprofiles/{profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "accountPermissions": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{profileId}/accountPermissions/{id}",
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.accountPermissions.list",
          "path": "userprofiles/{profileId}/accountPermissions",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "accountUserProfiles": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.accountUserProfiles.get",
          "path": "userprofiles/{profileId}/accountUserProfiles/{id}",
          "httpMethod": "GET",
          "description": "Gets one account user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.accountUserProfiles.insert",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "POST",
          "description": "Inserts a new account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.accountUserProfiles.list",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "GET",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.accountUserProfiles.patch",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "path": "userprofiles/{profileId}/accountUserProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "accounts": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.accounts.get",
          "path": "userprofiles/{profileId}/accounts/{id}",
          "httpMethod": "GET",
          "description": "Gets one account by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.accounts.list",
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "GET",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.accounts.patch",
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "PATCH",
          "description": "Updates an existing account. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.accounts.update",
          "path": "userprofiles/{profileId}/accounts",
          "httpMethod": "PUT",
          "description": "Updates an existing account.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "ads": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.ads.get",
          "path": "userprofiles/{profileId}/ads/{id}",
          "httpMethod": "GET",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.ads.insert",
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "POST",
          "description": "Inserts a new ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.ads.list",
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "GET",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.ads.patch",
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "PATCH",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.ads.update",
          "path": "userprofiles/{profileId}/ads",
          "httpMethod": "PUT",
          "description": "Updates an existing ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "advertiserGroups": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.advertiserGroups.get",
          "path": "userprofiles/{profileId}/advertiserGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one advertiser group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.advertiserGroups.insert",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.advertiserGroups.list",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.advertiserGroups.patch",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "path": "userprofiles/{profileId}/advertiserGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "advertiserLandingPages": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "path": "userprofiles/{profileId}/advertiserLandingPages/{id}",
          "httpMethod": "GET",
          "description": "Gets one landing page by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.advertiserLandingPages.insert",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "POST",
          "description": "Inserts a new landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.advertiserLandingPages.list",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "GET",
          "description": "Retrieves a list of landing pages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.advertiserLandingPages.patch",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser landing page. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.advertiserLandingPages.update",
          "path": "userprofiles/{profileId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "description": "Updates an existing landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "advertisers": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.advertisers.get",
          "path": "userprofiles/{profileId}/advertisers/{id}",
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.advertisers.insert",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.advertisers.list",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.advertisers.update",
          "path": "userprofiles/{profileId}/advertisers",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "browsers": {
      "resources": {},
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "path": "userprofiles/{profileId}/browsers",
          "httpMethod": "GET",
          "description": "Retrieves a list of browsers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "campaignCreativeAssociations": {
      "resources": {},
      "methods": {
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "path": "userprofiles/{profileId}/campaigns/{campaignId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "campaigns": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.campaigns.get",
          "path": "userprofiles/{profileId}/campaigns/{id}",
          "httpMethod": "GET",
          "description": "Gets one campaign by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.campaigns.insert",
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "POST",
          "description": "Inserts a new campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.campaigns.list",
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "GET",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.campaigns.patch",
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PATCH",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.campaigns.update",
          "path": "userprofiles/{profileId}/campaigns",
          "httpMethod": "PUT",
          "description": "Updates an existing campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "changeLogs": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{profileId}/changeLogs/{id}",
          "httpMethod": "GET",
          "description": "Gets one change log by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.changeLogs.list",
          "path": "userprofiles/{profileId}/changeLogs",
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "cities": {
      "resources": {},
      "methods": {
        "list": {
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{profileId}/cities",
          "httpMethod": "GET",
          "description": "Retrieves a list of cities, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "connectionTypes": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.connectionTypes.get",
          "path": "userprofiles/{profileId}/connectionTypes/{id}",
          "httpMethod": "GET",
          "description": "Gets one connection type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.connectionTypes.list",
          "path": "userprofiles/{profileId}/connectionTypes",
          "httpMethod": "GET",
          "description": "Retrieves a list of connection types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "contentCategories": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.contentCategories.delete",
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.contentCategories.get",
          "path": "userprofiles/{profileId}/contentCategories/{id}",
          "httpMethod": "GET",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.contentCategories.insert",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "POST",
          "description": "Inserts a new content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.contentCategories.list",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "GET",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.contentCategories.patch",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.contentCategories.update",
          "path": "userprofiles/{profileId}/contentCategories",
          "httpMethod": "PUT",
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "conversions": {
      "resources": {},
      "methods": {
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "description": "Inserts conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "batchupdate": {
          "id": "dfareporting.conversions.batchupdate",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "description": "Updates existing conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "countries": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.countries.get",
          "path": "userprofiles/{profileId}/countries/{dartId}",
          "httpMethod": "GET",
          "description": "Gets one country by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.countries.list",
          "path": "userprofiles/{profileId}/countries",
          "httpMethod": "GET",
          "description": "Retrieves a list of countries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "creativeAssets": {
      "resources": {},
      "methods": {
        "insert": {
          "id": "dfareporting.creativeAssets.insert",
          "path": "userprofiles/{profileId}/creativeAssets/{advertiserId}/creativeAssets",
          "httpMethod": "POST",
          "description": "Inserts a new creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": true
        }
      }
    },
    "creativeFieldValues": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.creativeFieldValues.delete",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.creativeFieldValues.get",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues/{id}",
          "httpMethod": "GET",
          "description": "Gets one creative field value by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "POST",
          "description": "Inserts a new creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{profileId}/creativeFields/{creativeFieldId}/creativeFieldValues",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "creativeFields": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.creativeFields.delete",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.creativeFields.get",
          "path": "userprofiles/{profileId}/creativeFields/{id}",
          "httpMethod": "GET",
          "description": "Gets one creative field by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "POST",
          "description": "Inserts a new creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.creativeFields.list",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.creativeFields.patch",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.creativeFields.update",
          "path": "userprofiles/{profileId}/creativeFields",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "creativeGroups": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.creativeGroups.get",
          "path": "userprofiles/{profileId}/creativeGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one creative group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.creativeGroups.insert",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "POST",
          "description": "Inserts a new creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.creativeGroups.list",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{profileId}/creativeGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "creatives": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{profileId}/creatives/{id}",
          "httpMethod": "GET",
          "description": "Gets one creative by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.creatives.insert",
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "POST",
          "description": "Inserts a new creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.creatives.list",
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "GET",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.creatives.update",
          "path": "userprofiles/{profileId}/creatives",
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "customEvents": {
      "resources": {},
      "methods": {
        "batchinsert": {
          "id": "dfareporting.customEvents.batchinsert",
          "path": "userprofiles/{profileId}/customEvents/batchinsert",
          "httpMethod": "POST",
          "description": "Inserts custom events.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "dimensionValues": {
      "resources": {},
      "methods": {
        "query": {
          "id": "dfareporting.dimensionValues.query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "directorySites": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.directorySites.get",
          "path": "userprofiles/{profileId}/directorySites/{id}",
          "httpMethod": "GET",
          "description": "Gets one directory site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.directorySites.insert",
          "path": "userprofiles/{profileId}/directorySites",
          "httpMethod": "POST",
          "description": "Inserts a new directory site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.directorySites.list",
          "path": "userprofiles/{profileId}/directorySites",
          "httpMethod": "GET",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "dynamicTargetingKeys": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys/{objectId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.dynamicTargetingKeys.list",
          "path": "userprofiles/{profileId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "description": "Retrieves a list of dynamic targeting keys.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "eventTags": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.eventTags.delete",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.eventTags.get",
          "path": "userprofiles/{profileId}/eventTags/{id}",
          "httpMethod": "GET",
          "description": "Gets one event tag by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "POST",
          "description": "Inserts a new event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.eventTags.list",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "GET",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.eventTags.update",
          "path": "userprofiles/{profileId}/eventTags",
          "httpMethod": "PUT",
          "description": "Updates an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "files": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.files.get",
          "path": "reports/{reportId}/files/{fileId}",
          "httpMethod": "GET",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.files.list",
          "path": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "description": "Lists files for a user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "floodlightActivities": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.floodlightActivities.delete",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "path": "userprofiles/{profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "description": "Generates a tag for a floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "path": "userprofiles/{profileId}/floodlightActivities/{id}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "path": "userprofiles/{profileId}/floodlightActivities",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "floodlightActivityGroups": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "path": "userprofiles/{profileId}/floodlightActivityGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.floodlightActivityGroups.insert",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.floodlightActivityGroups.patch",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "path": "userprofiles/{profileId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "floodlightConfigurations": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.floodlightConfigurations.get",
          "path": "userprofiles/{profileId}/floodlightConfigurations/{id}",
          "httpMethod": "GET",
          "description": "Gets one floodlight configuration by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.floodlightConfigurations.list",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.floodlightConfigurations.patch",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.floodlightConfigurations.update",
          "path": "userprofiles/{profileId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight configuration.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "inventoryItems": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.inventoryItems.get",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems/{id}",
          "httpMethod": "GET",
          "description": "Gets one inventory item by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.inventoryItems.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "languages": {
      "resources": {},
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "path": "userprofiles/{profileId}/languages",
          "httpMethod": "GET",
          "description": "Retrieves a list of languages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "metros": {
      "resources": {},
      "methods": {
        "list": {
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{profileId}/metros",
          "httpMethod": "GET",
          "description": "Retrieves a list of metros.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "mobileApps": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.mobileApps.get",
          "path": "userprofiles/{profileId}/mobileApps/{id}",
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{profileId}/mobileApps",
          "httpMethod": "GET",
          "description": "Retrieves list of available mobile apps.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "mobileCarriers": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.mobileCarriers.get",
          "path": "userprofiles/{profileId}/mobileCarriers/{id}",
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.mobileCarriers.list",
          "path": "userprofiles/{profileId}/mobileCarriers",
          "httpMethod": "GET",
          "description": "Retrieves a list of mobile carriers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "operatingSystemVersions": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystemVersions.get",
          "path": "userprofiles/{profileId}/operatingSystemVersions/{id}",
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "path": "userprofiles/{profileId}/operatingSystemVersions",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "operatingSystems": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystems.get",
          "path": "userprofiles/{profileId}/operatingSystems/{dartId}",
          "httpMethod": "GET",
          "description": "Gets one operating system by DART ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.operatingSystems.list",
          "path": "userprofiles/{profileId}/operatingSystems",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating systems.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "orderDocuments": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.orderDocuments.get",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments/{id}",
          "httpMethod": "GET",
          "description": "Gets one order document by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.orderDocuments.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orderDocuments",
          "httpMethod": "GET",
          "description": "Retrieves a list of order documents, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "orders": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.orders.get",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders/{id}",
          "httpMethod": "GET",
          "description": "Gets one order by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.orders.list",
          "path": "userprofiles/{profileId}/projects/{projectId}/orders",
          "httpMethod": "GET",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "placementGroups": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.placementGroups.get",
          "path": "userprofiles/{profileId}/placementGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "POST",
          "description": "Inserts a new placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.placementGroups.list",
          "path": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "path": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "path": "userprofiles/{profileId}/placementGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "placementStrategies": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.placementStrategies.delete",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "path": "userprofiles/{profileId}/placementStrategies/{id}",
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.placementStrategies.insert",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "POST",
          "description": "Inserts a new placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.placementStrategies.list",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "path": "userprofiles/{profileId}/placementStrategies",
          "httpMethod": "PUT",
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "placements": {
      "resources": {},
      "methods": {
        "generatetags": {
          "id": "dfareporting.placements.generatetags",
          "path": "userprofiles/{profileId}/placements/generatetags",
          "httpMethod": "POST",
          "description": "Generates tags for a placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.placements.get",
          "path": "userprofiles/{profileId}/placements/{id}",
          "httpMethod": "GET",
          "description": "Gets one placement by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "POST",
          "description": "Inserts a new placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.placements.list",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "GET",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.placements.update",
          "path": "userprofiles/{profileId}/placements",
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "platformTypes": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.platformTypes.get",
          "path": "userprofiles/{profileId}/platformTypes/{id}",
          "httpMethod": "GET",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.platformTypes.list",
          "path": "userprofiles/{profileId}/platformTypes",
          "httpMethod": "GET",
          "description": "Retrieves a list of platform types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "postalCodes": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.postalCodes.get",
          "path": "userprofiles/{profileId}/postalCodes/{code}",
          "httpMethod": "GET",
          "description": "Gets one postal code by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.postalCodes.list",
          "path": "userprofiles/{profileId}/postalCodes",
          "httpMethod": "GET",
          "description": "Retrieves a list of postal codes.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "projects": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.projects.get",
          "path": "userprofiles/{profileId}/projects/{id}",
          "httpMethod": "GET",
          "description": "Gets one project by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.projects.list",
          "path": "userprofiles/{profileId}/projects",
          "httpMethod": "GET",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "regions": {
      "resources": {},
      "methods": {
        "list": {
          "id": "dfareporting.regions.list",
          "path": "userprofiles/{profileId}/regions",
          "httpMethod": "GET",
          "description": "Retrieves a list of regions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "remarketingListShares": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.remarketingListShares.get",
          "path": "userprofiles/{profileId}/remarketingListShares/{remarketingListId}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.remarketingListShares.update",
          "path": "userprofiles/{profileId}/remarketingListShares",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list share.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "remarketingLists": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.remarketingLists.get",
          "path": "userprofiles/{profileId}/remarketingLists/{id}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "POST",
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.remarketingLists.list",
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "GET",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.remarketingLists.patch",
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.remarketingLists.update",
          "path": "userprofiles/{profileId}/remarketingLists",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "reports": {
      "resources": {
        "compatibleFields": {
          "resources": {},
          "methods": {
            "query": {
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "files": {
          "resources": {},
          "methods": {
            "get": {
              "id": "dfareporting.reports.files.get",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": true,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "dfareporting.reports.files.list",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "delete": {
          "id": "dfareporting.reports.delete",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "description": "Deletes a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.reports.get",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "description": "Creates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.reports.list",
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "GET",
          "description": "Retrieves list of reports.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.reports.patch",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing report. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "run": {
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "description": "Runs a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.reports.update",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "sites": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.sites.get",
          "path": "userprofiles/{profileId}/sites/{id}",
          "httpMethod": "GET",
          "description": "Gets one site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.sites.insert",
          "path": "userprofiles/{profileId}/sites",
          "httpMethod": "POST",
          "description": "Inserts a new site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.sites.list",
          "path": "userprofiles/{profileId}/sites",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.sites.patch",
          "path": "userprofiles/{profileId}/sites",
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.sites.update",
          "path": "userprofiles/{profileId}/sites",
          "httpMethod": "PUT",
          "description": "Updates an existing site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "sizes": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.sizes.get",
          "path": "userprofiles/{profileId}/sizes/{id}",
          "httpMethod": "GET",
          "description": "Gets one size by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.sizes.insert",
          "path": "userprofiles/{profileId}/sizes",
          "httpMethod": "POST",
          "description": "Inserts a new size.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.sizes.list",
          "path": "userprofiles/{profileId}/sizes",
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "subaccounts": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.subaccounts.get",
          "path": "userprofiles/{profileId}/subaccounts/{id}",
          "httpMethod": "GET",
          "description": "Gets one subaccount by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.subaccounts.insert",
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "POST",
          "description": "Inserts a new subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.subaccounts.list",
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "GET",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PATCH",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.subaccounts.update",
          "path": "userprofiles/{profileId}/subaccounts",
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "targetableRemarketingLists": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.targetableRemarketingLists.get",
          "path": "userprofiles/{profileId}/targetableRemarketingLists/{id}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.targetableRemarketingLists.list",
          "path": "userprofiles/{profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "targetingTemplates": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.targetingTemplates.get",
          "path": "userprofiles/{profileId}/targetingTemplates/{id}",
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.targetingTemplates.insert",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "POST",
          "description": "Inserts a new targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.targetingTemplates.list",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "GET",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "PATCH",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.targetingTemplates.update",
          "path": "userprofiles/{profileId}/targetingTemplates",
          "httpMethod": "PUT",
          "description": "Updates an existing targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "userProfiles": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.userProfiles.get",
          "path": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.userProfiles.list",
          "path": "userprofiles",
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "userRolePermissionGroups": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.userRolePermissionGroups.get",
          "path": "userprofiles/{profileId}/userRolePermissionGroups/{id}",
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "userRolePermissions": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.userRolePermissions.get",
          "path": "userprofiles/{profileId}/userRolePermissions/{id}",
          "httpMethod": "GET",
          "description": "Gets one user role permission by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.userRolePermissions.list",
          "path": "userprofiles/{profileId}/userRolePermissions",
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "userRoles": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "dfareporting.userRoles.get",
          "path": "userprofiles/{profileId}/userRoles/{id}",
          "httpMethod": "GET",
          "description": "Gets one user role by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "POST",
          "description": "Inserts a new user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "GET",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "dfareporting.userRoles.patch",
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "dfareporting.userRoles.update",
          "path": "userprofiles/{profileId}/userRoles",
          "httpMethod": "PUT",
          "description": "Updates an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "videoFormats": {
      "resources": {},
      "methods": {
        "get": {
          "id": "dfareporting.videoFormats.get",
          "path": "userprofiles/{profileId}/videoFormats/{id}",
          "httpMethod": "GET",
          "description": "Gets one video format by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "dfareporting.videoFormats.list",
          "path": "userprofiles/{profileId}/videoFormats",
          "httpMethod": "GET",
          "description": "Lists available video formats.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}