{
  "kind": "discovery#restDescription",
  "etag": null,
  "discoveryVersion": "v1",
  "id": "script:v1",
  "name": "script",
  "canonicalName": "Script",
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "revision": "20210227",
  "title": "Apps Script API",
  "description": "Manages and executes Google Apps Script projects. ",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "protocol": "rest",
  "baseUrl": "https://script.googleapis.com/",
  "basePath": "",
  "rootUrl": "https://script.googleapis.com/",
  "servicePath": "",
  "batchPath": "batch",
  "version_module": null,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/documents": {
          "description": "See, create, and edit all Google Docs documents you have access to"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete your spreadsheets in Google Drive"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "View your email address"
        }
      }
    }
  },
  "resources": {
    "processes": {
      "resources": {},
      "methods": {
        "list": {
          "id": "script.processes.list",
          "path": "v1/processes",
          "httpMethod": "GET",
          "description": "List information about processes made by or on behalf of a user, such as process type and current status.",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "listScriptProcesses": {
          "id": "script.processes.listScriptProcesses",
          "path": "v1/processes:listScriptProcesses",
          "httpMethod": "GET",
          "description": "List information about a script's executed processes, such as process type and current status.",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "projects": {
      "resources": {
        "deployments": {
          "resources": {},
          "methods": {
            "create": {
              "id": "script.projects.deployments.create",
              "path": "v1/projects/{scriptId}/deployments",
              "httpMethod": "POST",
              "description": "Creates a deployment of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "delete": {
              "id": "script.projects.deployments.delete",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "DELETE",
              "description": "Deletes a deployment of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "script.projects.deployments.get",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "GET",
              "description": "Gets a deployment of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "script.projects.deployments.list",
              "path": "v1/projects/{scriptId}/deployments",
              "httpMethod": "GET",
              "description": "Lists the deployments of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "update": {
              "id": "script.projects.deployments.update",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "httpMethod": "PUT",
              "description": "Updates a deployment of an Apps Script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "versions": {
          "resources": {},
          "methods": {
            "create": {
              "id": "script.projects.versions.create",
              "path": "v1/projects/{scriptId}/versions",
              "httpMethod": "POST",
              "description": "Creates a new immutable version using the current code, with a unique version number.",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "script.projects.versions.get",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}",
              "httpMethod": "GET",
              "description": "Gets a version of a script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "script.projects.versions.list",
              "path": "v1/projects/{scriptId}/versions",
              "httpMethod": "GET",
              "description": "List the versions of a script project.",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "create": {
          "id": "script.projects.create",
          "path": "v1/projects",
          "httpMethod": "POST",
          "description": "Creates a new, empty script project with no script files and a base manifest file.",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "script.projects.get",
          "path": "v1/projects/{scriptId}",
          "httpMethod": "GET",
          "description": "Gets a script project's metadata.",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "getContent": {
          "id": "script.projects.getContent",
          "path": "v1/projects/{scriptId}/content",
          "httpMethod": "GET",
          "description": "Gets the content of the script project, including the code source and metadata for each script file.",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "getMetrics": {
          "id": "script.projects.getMetrics",
          "path": "v1/projects/{scriptId}/metrics",
          "httpMethod": "GET",
          "description": "Get metrics data for scripts, such as number of executions and active users.",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "updateContent": {
          "id": "script.projects.updateContent",
          "path": "v1/projects/{scriptId}/content",
          "httpMethod": "PUT",
          "description": "Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project.",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "scripts": {
      "resources": {},
      "methods": {
        "run": {
          "id": "script.scripts.run",
          "path": "v1/scripts/{scriptId}:run",
          "httpMethod": "POST",
          "description": "Runs a function in an Apps Script project. The script project must be deployed for use with the Apps Script API and the calling application must share the same Cloud Platform project. This method requires authorization with an OAuth 2.0 token that includes at least one of the scopes listed in the [Authorization](#authorization-scopes) section; script projects that do not require authorization cannot be executed through this API. To find the correct scopes to include in [...]",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}