{
  "kind": "discovery#restDescription",
  "etag": "\"LYADMvHWYH2ul9D6m9UT9gT77YM/EQbuV7RCJTKzgEWKaE9OS8b021Q\"",
  "discoveryVersion": "v1",
  "id": "analytics:v2.4",
  "name": "analytics",
  "canonicalName": null,
  "fullyEncodeReservedExpansion": null,
  "version": "v2.4",
  "revision": "20190917",
  "title": "Google Analytics API",
  "description": "Views and manages your Google Analytics data.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/analytics/",
  "protocol": "rest",
  "baseUrl": "https://www.googleapis.com/analytics/v2.4/",
  "basePath": "/analytics/v2.4/",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "analytics/v2.4/",
  "batchPath": "batch/analytics/v2.4",
  "version_module": null,
  "packagePath": null,
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "View your Google Analytics data"
        }
      }
    }
  },
  "resources": {
    "data": {
      "resources": {},
      "methods": {
        "get": {
          "id": "analytics.data.get",
          "path": "data",
          "httpMethod": "GET",
          "description": "Returns Analytics report data for a view (profile).",
          "scopes": [
            "https://www.googleapis.com/auth/analytics",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "management": {
      "resources": {
        "accounts": {
          "resources": {},
          "methods": {
            "list": {
              "id": "analytics.management.accounts.list",
              "path": "management/accounts",
              "httpMethod": "GET",
              "description": "Lists all accounts to which the user has access.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "goals": {
          "resources": {},
          "methods": {
            "list": {
              "id": "analytics.management.goals.list",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
              "httpMethod": "GET",
              "description": "Lists goals to which the user has access.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "profiles": {
          "resources": {},
          "methods": {
            "list": {
              "id": "analytics.management.profiles.list",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
              "httpMethod": "GET",
              "description": "Lists views (profiles) to which the user has access.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "segments": {
          "resources": {},
          "methods": {
            "list": {
              "id": "analytics.management.segments.list",
              "path": "management/segments",
              "httpMethod": "GET",
              "description": "Lists advanced segments to which the user has access.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "webproperties": {
          "resources": {},
          "methods": {
            "list": {
              "id": "analytics.management.webproperties.list",
              "path": "management/accounts/{accountId}/webproperties",
              "httpMethod": "GET",
              "description": "Lists web properties to which the user has access.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {}
    }
  },
  "methods": {}
}