MCP ?= ../generator/target/release/mcp
SHELL = /bin/bash

help:
	$(info -- Individual Targets ----------------------------------------------------------------)
	$(info -- Run target <name> like `make foo-cargo ARGS="check" to invoke cargo ---------------)
	$(info --------------------------------------------------------------------------------------)
{% for item in api -%}
	$(info {{ item.make_target }})
{% endfor -%}
	$(info -- Combined Targets ------------------------------------------------------------------)
	$(info gen-all             | generate all libraries and CLIs)
	$(info cargo-all           | pass args with ARGS="check" for example)
	$(info --------------------------------------------------------------------------------------)

gen-all: {% for item in api -%}{{item.make_target}} {% endfor %}
	@echo "Consider running the following line to ignore crates with errors"
	@echo $(MAKE) -C .. update-drivers
cargo-all: {% for item in api -%}{{item.make_target}}-cargo {% endfor %}

{% for item in api %}
{{item.lib_cargo_file}}: ../{{standard.spec_dir}}/{{item.spec_file}} $(MCP)
	set -o pipefail; $(MCP) generate $< {{item.gen_dir}} 2>&1 | tee {{item.gen_error_file}} && rm {{item.gen_error_file}}
{{item.make_target}}: {{item.lib_cargo_file}}
{{item.make_target}}-cargo: {{item.make_target}}
	set -o pipefail; ( cd {{item.gen_dir}}/{{standard.lib_dir}} && cargo $(ARGS) ) 2>&1 | tee {{item.cargo_error_file}} && rm {{item.cargo_error_file}}
{% endfor %}