MCP ?= ../generator/target/release/mcp

help:
	$(info -- Target ----------------------------------------------------------------------------)
	$(info gen-all             | generate all libraries and CLIs)
	$(info cargo-all           | pass args with ARGS="check" for example)
	$(info --------------------------------------------------------------------------------------)

gen-all: {% for item in api -%}{{item.make_target}} {% endfor %}
	@echo "Consider running the following line to ignore crates with errors"
	@echo $(MAKE) -C .. update-mapped-index
cargo-all: {% for item in api -%}{{item.make_target}}-cargo {% endfor %}

{% for item in api %}
{{item.lib_cargo_file}}: {{item.spec_file}} $(MCP)
	$(MCP) generate $< {{item.gen_dir}} 2>{{item.error_file}} && rm {{item.error_file}}
{{item.make_target}}: {{item.lib_cargo_file}}
{{item.make_target}}-cargo: {{item.make_target}}
	( cd {{item.gen_dir}}/{{standard.lib_dir}} && cargo $(ARGS) ) 2> {{item.error_file}} && rm {{item.error_file}}
{% endfor %}