[package]

name = "google-cli-shared"
version = "0.1.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
description = "Code shared by all Google CLI crates"
edition = "2018"
publish = false

[dependencies]
mime = "^ 0.3.13"
serde_json = "^ 1.0"
yup-oauth2 = "^3.1"
strsim = "^0.9"

[workspace]
