{
  "kind": "discovery#restDescription",
  "etag": "\"u9GIe6H63LSGq-9_t39K2Zx_EAc/6ejmeqs8pIMfxzC9gWby_uKyvCk\"",
  "discoveryVersion": "v1",
  "id": "admin:directory_v1",
  "name": "admin",
  "canonicalName": "directory",
  "fullyEncodeReservedExpansion": null,
  "version": "directory_v1",
  "revision": "20200605",
  "title": "Admin Directory API",
  "description": "Manages enterprise resources such as users and groups, administrative notifications, security features, and more.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/admin-sdk/directory/",
  "protocol": "rest",
  "baseUrl": "https://www.googleapis.com/admin/directory/v1/",
  "basePath": "/admin/directory/v1/",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "admin/directory/v1/",
  "batchPath": "batch/admin/directory_v1",
  "version_module": null,
  "packagePath": "admin",
  "labels": null,
  "features": null,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/admin.directory.customer": {
          "description": "View and manage customer related information"
        },
        "https://www.googleapis.com/auth/admin.directory.customer.readonly": {
          "description": "View customer related information"
        },
        "https://www.googleapis.com/auth/admin.directory.device.chromeos": {
          "description": "View and manage your Chrome OS devices' metadata"
        },
        "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly": {
          "description": "View your Chrome OS devices' metadata"
        },
        "https://www.googleapis.com/auth/admin.directory.device.mobile": {
          "description": "View and manage your mobile devices' metadata"
        },
        "https://www.googleapis.com/auth/admin.directory.device.mobile.action": {
          "description": "Manage your mobile devices by performing administrative tasks"
        },
        "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly": {
          "description": "View your mobile devices' metadata"
        },
        "https://www.googleapis.com/auth/admin.directory.domain": {
          "description": "View and manage the provisioning of domains for your customers"
        },
        "https://www.googleapis.com/auth/admin.directory.domain.readonly": {
          "description": "View domains related to your customers"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.group.member": {
          "description": "View and manage group subscriptions on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.group.member.readonly": {
          "description": "View group subscriptions on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.group.readonly": {
          "description": "View groups on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.notifications": {
          "description": "View and manage notifications received on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.orgunit": {
          "description": "View and manage organization units on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.orgunit.readonly": {
          "description": "View organization units on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.resource.calendar": {
          "description": "View and manage the provisioning of calendar resources on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly": {
          "description": "View calendar resources on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.rolemanagement": {
          "description": "Manage delegated admin roles for your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly": {
          "description": "View delegated admin roles for your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user.alias": {
          "description": "View and manage user aliases on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user.alias.readonly": {
          "description": "View user aliases on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user.readonly": {
          "description": "View users on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.user.security": {
          "description": "Manage data access permissions for users on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.userschema": {
          "description": "View and manage the provisioning of user schemas on your domain"
        },
        "https://www.googleapis.com/auth/admin.directory.userschema.readonly": {
          "description": "View user schemas on your domain"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "View and manage your data across Google Cloud Platform services"
        }
      }
    }
  },
  "resources": {
    "asps": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.asps.delete",
          "path": "users/{userKey}/asps/{codeId}",
          "httpMethod": "DELETE",
          "description": "Delete an ASP issued by a user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.asps.get",
          "path": "users/{userKey}/asps/{codeId}",
          "httpMethod": "GET",
          "description": "Get information about an ASP issued by a user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.asps.list",
          "path": "users/{userKey}/asps",
          "httpMethod": "GET",
          "description": "List the ASPs issued by a user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "channels": {
      "resources": {},
      "methods": {
        "stop": {
          "id": "admin.channels.stop",
          "path": "/admin/directory_v1/channels/stop",
          "httpMethod": "POST",
          "description": "Stop watching resources through this channel",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/admin.directory.user.alias",
            "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
            "https://www.googleapis.com/auth/admin.directory.user.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "chromeosdevices": {
      "resources": {},
      "methods": {
        "action": {
          "id": "directory.chromeosdevices.action",
          "path": "customer/{customerId}/devices/chromeos/{resourceId}/action",
          "httpMethod": "POST",
          "description": "Take action on Chrome OS Device",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.chromeosdevices.get",
          "path": "customer/{customerId}/devices/chromeos/{deviceId}",
          "httpMethod": "GET",
          "description": "Retrieve Chrome OS Device",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos",
            "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.chromeosdevices.list",
          "path": "customer/{customerId}/devices/chromeos",
          "httpMethod": "GET",
          "description": "Retrieve all Chrome OS Devices of a customer (paginated)",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos",
            "https://www.googleapis.com/auth/admin.directory.device.chromeos.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "moveDevicesToOu": {
          "id": "directory.chromeosdevices.moveDevicesToOu",
          "path": "customer/{customerId}/devices/chromeos/moveDevicesToOu",
          "httpMethod": "POST",
          "description": "Move or insert multiple Chrome OS Devices to organizational unit",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.chromeosdevices.patch",
          "path": "customer/{customerId}/devices/chromeos/{deviceId}",
          "httpMethod": "PATCH",
          "description": "Update Chrome OS Device. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.chromeosdevices.update",
          "path": "customer/{customerId}/devices/chromeos/{deviceId}",
          "httpMethod": "PUT",
          "description": "Update Chrome OS Device",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.chromeos"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "customers": {
      "resources": {},
      "methods": {
        "get": {
          "id": "directory.customers.get",
          "path": "customers/{customerKey}",
          "httpMethod": "GET",
          "description": "Retrieves a customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.customer",
            "https://www.googleapis.com/auth/admin.directory.customer.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.customers.patch",
          "path": "customers/{customerKey}",
          "httpMethod": "PATCH",
          "description": "Updates a customer. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.customer"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.customers.update",
          "path": "customers/{customerKey}",
          "httpMethod": "PUT",
          "description": "Updates a customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.customer"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "domainAliases": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.domainAliases.delete",
          "path": "customer/{customer}/domainaliases/{domainAliasName}",
          "httpMethod": "DELETE",
          "description": "Deletes a Domain Alias of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.domainAliases.get",
          "path": "customer/{customer}/domainaliases/{domainAliasName}",
          "httpMethod": "GET",
          "description": "Retrieves a domain alias of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain",
            "https://www.googleapis.com/auth/admin.directory.domain.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.domainAliases.insert",
          "path": "customer/{customer}/domainaliases",
          "httpMethod": "POST",
          "description": "Inserts a Domain alias of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.domainAliases.list",
          "path": "customer/{customer}/domainaliases",
          "httpMethod": "GET",
          "description": "Lists the domain aliases of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain",
            "https://www.googleapis.com/auth/admin.directory.domain.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "domains": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.domains.delete",
          "path": "customer/{customer}/domains/{domainName}",
          "httpMethod": "DELETE",
          "description": "Deletes a domain of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.domains.get",
          "path": "customer/{customer}/domains/{domainName}",
          "httpMethod": "GET",
          "description": "Retrieves a domain of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain",
            "https://www.googleapis.com/auth/admin.directory.domain.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.domains.insert",
          "path": "customer/{customer}/domains",
          "httpMethod": "POST",
          "description": "Inserts a domain of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.domains.list",
          "path": "customer/{customer}/domains",
          "httpMethod": "GET",
          "description": "Lists the domains of the customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.domain",
            "https://www.googleapis.com/auth/admin.directory.domain.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "groups": {
      "resources": {
        "aliases": {
          "resources": {},
          "methods": {
            "delete": {
              "id": "directory.groups.aliases.delete",
              "path": "groups/{groupKey}/aliases/{alias}",
              "httpMethod": "DELETE",
              "description": "Remove a alias for the group",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.group"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "insert": {
              "id": "directory.groups.aliases.insert",
              "path": "groups/{groupKey}/aliases",
              "httpMethod": "POST",
              "description": "Add a alias for the group",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.group"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "directory.groups.aliases.list",
              "path": "groups/{groupKey}/aliases",
              "httpMethod": "GET",
              "description": "List all aliases for a group",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.group",
                "https://www.googleapis.com/auth/admin.directory.group.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": true,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "delete": {
          "id": "directory.groups.delete",
          "path": "groups/{groupKey}",
          "httpMethod": "DELETE",
          "description": "Delete Group",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.groups.get",
          "path": "groups/{groupKey}",
          "httpMethod": "GET",
          "description": "Retrieve Group",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.groups.insert",
          "path": "groups",
          "httpMethod": "POST",
          "description": "Create Group",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.groups.list",
          "path": "groups",
          "httpMethod": "GET",
          "description": "Retrieve all groups of a domain or of a user given a userKey (paginated)",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.groups.patch",
          "path": "groups/{groupKey}",
          "httpMethod": "PATCH",
          "description": "Update Group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.groups.update",
          "path": "groups/{groupKey}",
          "httpMethod": "PUT",
          "description": "Update Group",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "members": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.members.delete",
          "path": "groups/{groupKey}/members/{memberKey}",
          "httpMethod": "DELETE",
          "description": "Remove membership.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.members.get",
          "path": "groups/{groupKey}/members/{memberKey}",
          "httpMethod": "GET",
          "description": "Retrieve Group Member",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member",
            "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "hasMember": {
          "id": "directory.members.hasMember",
          "path": "groups/{groupKey}/hasMember/{memberKey}",
          "httpMethod": "GET",
          "description": "Checks whether the given user is a member of the group. Membership can be direct or nested.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member",
            "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.members.insert",
          "path": "groups/{groupKey}/members",
          "httpMethod": "POST",
          "description": "Add user to the specified group.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.members.list",
          "path": "groups/{groupKey}/members",
          "httpMethod": "GET",
          "description": "Retrieve all members in a group (paginated)",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member",
            "https://www.googleapis.com/auth/admin.directory.group.member.readonly",
            "https://www.googleapis.com/auth/admin.directory.group.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.members.patch",
          "path": "groups/{groupKey}/members/{memberKey}",
          "httpMethod": "PATCH",
          "description": "Update membership of a user in the specified group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.members.update",
          "path": "groups/{groupKey}/members/{memberKey}",
          "httpMethod": "PUT",
          "description": "Update membership of a user in the specified group.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.group.member"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "mobiledevices": {
      "resources": {},
      "methods": {
        "action": {
          "id": "directory.mobiledevices.action",
          "path": "customer/{customerId}/devices/mobile/{resourceId}/action",
          "httpMethod": "POST",
          "description": "Take action on Mobile Device",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.mobile",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.action"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "delete": {
          "id": "directory.mobiledevices.delete",
          "path": "customer/{customerId}/devices/mobile/{resourceId}",
          "httpMethod": "DELETE",
          "description": "Delete Mobile Device",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.mobile"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.mobiledevices.get",
          "path": "customer/{customerId}/devices/mobile/{resourceId}",
          "httpMethod": "GET",
          "description": "Retrieve Mobile Device",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.mobile",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.mobiledevices.list",
          "path": "customer/{customerId}/devices/mobile",
          "httpMethod": "GET",
          "description": "Retrieve all Mobile Devices of a customer (paginated)",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.device.mobile",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.action",
            "https://www.googleapis.com/auth/admin.directory.device.mobile.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "notifications": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.notifications.delete",
          "path": "customer/{customer}/notifications/{notificationId}",
          "httpMethod": "DELETE",
          "description": "Deletes a notification",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.notifications"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.notifications.get",
          "path": "customer/{customer}/notifications/{notificationId}",
          "httpMethod": "GET",
          "description": "Retrieves a notification.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.notifications"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.notifications.list",
          "path": "customer/{customer}/notifications",
          "httpMethod": "GET",
          "description": "Retrieves a list of notifications.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.notifications"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.notifications.patch",
          "path": "customer/{customer}/notifications/{notificationId}",
          "httpMethod": "PATCH",
          "description": "Updates a notification. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.notifications"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.notifications.update",
          "path": "customer/{customer}/notifications/{notificationId}",
          "httpMethod": "PUT",
          "description": "Updates a notification.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.notifications"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "orgunits": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.orgunits.delete",
          "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
          "httpMethod": "DELETE",
          "description": "Remove organizational unit",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.orgunits.get",
          "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
          "httpMethod": "GET",
          "description": "Retrieve organizational unit",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit",
            "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.orgunits.insert",
          "path": "customer/{customerId}/orgunits",
          "httpMethod": "POST",
          "description": "Add organizational unit",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.orgunits.list",
          "path": "customer/{customerId}/orgunits",
          "httpMethod": "GET",
          "description": "Retrieve all organizational units",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit",
            "https://www.googleapis.com/auth/admin.directory.orgunit.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.orgunits.patch",
          "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
          "httpMethod": "PATCH",
          "description": "Update organizational unit. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.orgunits.update",
          "path": "customer/{customerId}/orgunits{/orgUnitPath*}",
          "httpMethod": "PUT",
          "description": "Update organizational unit",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.orgunit"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "privileges": {
      "resources": {},
      "methods": {
        "list": {
          "id": "directory.privileges.list",
          "path": "customer/{customer}/roles/ALL/privileges",
          "httpMethod": "GET",
          "description": "Retrieves a paginated list of all privileges for a customer.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "resources": {
      "resources": {
        "buildings": {
          "resources": {},
          "methods": {
            "delete": {
              "id": "directory.resources.buildings.delete",
              "path": "customer/{customer}/resources/buildings/{buildingId}",
              "httpMethod": "DELETE",
              "description": "Deletes a building.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "directory.resources.buildings.get",
              "path": "customer/{customer}/resources/buildings/{buildingId}",
              "httpMethod": "GET",
              "description": "Retrieves a building.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "insert": {
              "id": "directory.resources.buildings.insert",
              "path": "customer/{customer}/resources/buildings",
              "httpMethod": "POST",
              "description": "Inserts a building.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "directory.resources.buildings.list",
              "path": "customer/{customer}/resources/buildings",
              "httpMethod": "GET",
              "description": "Retrieves a list of buildings for an account.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "directory.resources.buildings.patch",
              "path": "customer/{customer}/resources/buildings/{buildingId}",
              "httpMethod": "PATCH",
              "description": "Updates a building. This method supports patch semantics.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "update": {
              "id": "directory.resources.buildings.update",
              "path": "customer/{customer}/resources/buildings/{buildingId}",
              "httpMethod": "PUT",
              "description": "Updates a building.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "calendars": {
          "resources": {},
          "methods": {
            "delete": {
              "id": "directory.resources.calendars.delete",
              "path": "customer/{customer}/resources/calendars/{calendarResourceId}",
              "httpMethod": "DELETE",
              "description": "Deletes a calendar resource.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "directory.resources.calendars.get",
              "path": "customer/{customer}/resources/calendars/{calendarResourceId}",
              "httpMethod": "GET",
              "description": "Retrieves a calendar resource.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "insert": {
              "id": "directory.resources.calendars.insert",
              "path": "customer/{customer}/resources/calendars",
              "httpMethod": "POST",
              "description": "Inserts a calendar resource.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "directory.resources.calendars.list",
              "path": "customer/{customer}/resources/calendars",
              "httpMethod": "GET",
              "description": "Retrieves a list of calendar resources for an account.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "directory.resources.calendars.patch",
              "path": "customer/{customer}/resources/calendars/{calendarResourceId}",
              "httpMethod": "PATCH",
              "description": "Updates a calendar resource.\n\nThis method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved. This method supports patch semantics.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "update": {
              "id": "directory.resources.calendars.update",
              "path": "customer/{customer}/resources/calendars/{calendarResourceId}",
              "httpMethod": "PUT",
              "description": "Updates a calendar resource.\n\nThis method supports patch semantics, meaning you only need to include the fields you wish to update. Fields that are not present in the request will be preserved.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        },
        "features": {
          "resources": {},
          "methods": {
            "delete": {
              "id": "directory.resources.features.delete",
              "path": "customer/{customer}/resources/features/{featureKey}",
              "httpMethod": "DELETE",
              "description": "Deletes a feature.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "directory.resources.features.get",
              "path": "customer/{customer}/resources/features/{featureKey}",
              "httpMethod": "GET",
              "description": "Retrieves a feature.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "insert": {
              "id": "directory.resources.features.insert",
              "path": "customer/{customer}/resources/features",
              "httpMethod": "POST",
              "description": "Inserts a feature.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "directory.resources.features.list",
              "path": "customer/{customer}/resources/features",
              "httpMethod": "GET",
              "description": "Retrieves a list of features for an account.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar",
                "https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "directory.resources.features.patch",
              "path": "customer/{customer}/resources/features/{featureKey}",
              "httpMethod": "PATCH",
              "description": "Updates a feature. This method supports patch semantics.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "rename": {
              "id": "directory.resources.features.rename",
              "path": "customer/{customer}/resources/features/{oldName}/rename",
              "httpMethod": "POST",
              "description": "Renames a feature.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "update": {
              "id": "directory.resources.features.update",
              "path": "customer/{customer}/resources/features/{featureKey}",
              "httpMethod": "PUT",
              "description": "Updates a feature.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.resource.calendar"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {}
    },
    "roleAssignments": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.roleAssignments.delete",
          "path": "customer/{customer}/roleassignments/{roleAssignmentId}",
          "httpMethod": "DELETE",
          "description": "Deletes a role assignment.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.roleAssignments.get",
          "path": "customer/{customer}/roleassignments/{roleAssignmentId}",
          "httpMethod": "GET",
          "description": "Retrieve a role assignment.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.roleAssignments.insert",
          "path": "customer/{customer}/roleassignments",
          "httpMethod": "POST",
          "description": "Creates a role assignment.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.roleAssignments.list",
          "path": "customer/{customer}/roleassignments",
          "httpMethod": "GET",
          "description": "Retrieves a paginated list of all roleAssignments.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "roles": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.roles.delete",
          "path": "customer/{customer}/roles/{roleId}",
          "httpMethod": "DELETE",
          "description": "Deletes a role.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.roles.get",
          "path": "customer/{customer}/roles/{roleId}",
          "httpMethod": "GET",
          "description": "Retrieves a role.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.roles.insert",
          "path": "customer/{customer}/roles",
          "httpMethod": "POST",
          "description": "Creates a role.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.roles.list",
          "path": "customer/{customer}/roles",
          "httpMethod": "GET",
          "description": "Retrieves a paginated list of all the roles in a domain.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement",
            "https://www.googleapis.com/auth/admin.directory.rolemanagement.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.roles.patch",
          "path": "customer/{customer}/roles/{roleId}",
          "httpMethod": "PATCH",
          "description": "Updates a role. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.roles.update",
          "path": "customer/{customer}/roles/{roleId}",
          "httpMethod": "PUT",
          "description": "Updates a role.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.rolemanagement"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "schemas": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.schemas.delete",
          "path": "customer/{customerId}/schemas/{schemaKey}",
          "httpMethod": "DELETE",
          "description": "Delete schema",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.schemas.get",
          "path": "customer/{customerId}/schemas/{schemaKey}",
          "httpMethod": "GET",
          "description": "Retrieve schema",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema",
            "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.schemas.insert",
          "path": "customer/{customerId}/schemas",
          "httpMethod": "POST",
          "description": "Create schema.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.schemas.list",
          "path": "customer/{customerId}/schemas",
          "httpMethod": "GET",
          "description": "Retrieve all schemas for a customer",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema",
            "https://www.googleapis.com/auth/admin.directory.userschema.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.schemas.patch",
          "path": "customer/{customerId}/schemas/{schemaKey}",
          "httpMethod": "PATCH",
          "description": "Update schema. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.schemas.update",
          "path": "customer/{customerId}/schemas/{schemaKey}",
          "httpMethod": "PUT",
          "description": "Update schema",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.userschema"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "tokens": {
      "resources": {},
      "methods": {
        "delete": {
          "id": "directory.tokens.delete",
          "path": "users/{userKey}/tokens/{clientId}",
          "httpMethod": "DELETE",
          "description": "Delete all access tokens issued by a user for an application.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.tokens.get",
          "path": "users/{userKey}/tokens/{clientId}",
          "httpMethod": "GET",
          "description": "Get information about an access token issued by a user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.tokens.list",
          "path": "users/{userKey}/tokens",
          "httpMethod": "GET",
          "description": "Returns the set of tokens specified user has issued to 3rd party applications.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    },
    "users": {
      "resources": {
        "aliases": {
          "resources": {},
          "methods": {
            "delete": {
              "id": "directory.users.aliases.delete",
              "path": "users/{userKey}/aliases/{alias}",
              "httpMethod": "DELETE",
              "description": "Remove a alias for the user",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.alias"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "insert": {
              "id": "directory.users.aliases.insert",
              "path": "users/{userKey}/aliases",
              "httpMethod": "POST",
              "description": "Add a alias for the user",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.alias"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "list": {
              "id": "directory.users.aliases.list",
              "path": "users/{userKey}/aliases",
              "httpMethod": "GET",
              "description": "List all aliases for a user",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.alias",
                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                "https://www.googleapis.com/auth/admin.directory.user.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": true,
              "supportsMediaUpload": false
            },
            "watch": {
              "id": "directory.users.aliases.watch",
              "path": "users/{userKey}/aliases/watch",
              "httpMethod": "POST",
              "description": "Watch for changes in user aliases list",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.alias",
                "https://www.googleapis.com/auth/admin.directory.user.alias.readonly",
                "https://www.googleapis.com/auth/admin.directory.user.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": true,
              "supportsMediaUpload": false
            }
          }
        },
        "photos": {
          "resources": {},
          "methods": {
            "delete": {
              "id": "directory.users.photos.delete",
              "path": "users/{userKey}/photos/thumbnail",
              "httpMethod": "DELETE",
              "description": "Remove photos for the user",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "get": {
              "id": "directory.users.photos.get",
              "path": "users/{userKey}/photos/thumbnail",
              "httpMethod": "GET",
              "description": "Retrieve photo of a user",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user",
                "https://www.googleapis.com/auth/admin.directory.user.readonly"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "patch": {
              "id": "directory.users.photos.patch",
              "path": "users/{userKey}/photos/thumbnail",
              "httpMethod": "PATCH",
              "description": "Add a photo for the user. This method supports patch semantics.",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            },
            "update": {
              "id": "directory.users.photos.update",
              "path": "users/{userKey}/photos/thumbnail",
              "httpMethod": "PUT",
              "description": "Add a photo for the user",
              "scopes": [
                "https://www.googleapis.com/auth/admin.directory.user"
              ],
              "supportsMediaDownload": false,
              "useMediaDownloadService": false,
              "supportsSubscription": false,
              "supportsMediaUpload": false
            }
          }
        }
      },
      "methods": {
        "delete": {
          "id": "directory.users.delete",
          "path": "users/{userKey}",
          "httpMethod": "DELETE",
          "description": "Delete user",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "get": {
          "id": "directory.users.get",
          "path": "users/{userKey}",
          "httpMethod": "GET",
          "description": "retrieve user",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/admin.directory.user.readonly"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "insert": {
          "id": "directory.users.insert",
          "path": "users",
          "httpMethod": "POST",
          "description": "create user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.users.list",
          "path": "users",
          "httpMethod": "GET",
          "description": "Retrieve either deleted users or all users in a domain (paginated)",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/admin.directory.user.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": true,
          "supportsMediaUpload": false
        },
        "makeAdmin": {
          "id": "directory.users.makeAdmin",
          "path": "users/{userKey}/makeAdmin",
          "httpMethod": "POST",
          "description": "change admin status of a user",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "patch": {
          "id": "directory.users.patch",
          "path": "users/{userKey}",
          "httpMethod": "PATCH",
          "description": "update user. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "undelete": {
          "id": "directory.users.undelete",
          "path": "users/{userKey}/undelete",
          "httpMethod": "POST",
          "description": "Undelete a deleted user",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "update": {
          "id": "directory.users.update",
          "path": "users/{userKey}",
          "httpMethod": "PUT",
          "description": "update user",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "watch": {
          "id": "directory.users.watch",
          "path": "users/watch",
          "httpMethod": "POST",
          "description": "Watch for changes in users list",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/admin.directory.user.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": true,
          "supportsMediaUpload": false
        }
      }
    },
    "verificationCodes": {
      "resources": {},
      "methods": {
        "generate": {
          "id": "directory.verificationCodes.generate",
          "path": "users/{userKey}/verificationCodes/generate",
          "httpMethod": "POST",
          "description": "Generate new backup verification codes for the user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "invalidate": {
          "id": "directory.verificationCodes.invalidate",
          "path": "users/{userKey}/verificationCodes/invalidate",
          "httpMethod": "POST",
          "description": "Invalidate the current backup verification codes for the user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        },
        "list": {
          "id": "directory.verificationCodes.list",
          "path": "users/{userKey}/verificationCodes",
          "httpMethod": "GET",
          "description": "Returns the current set of valid backup verification codes for the specified user.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.directory.user.security"
          ],
          "supportsMediaDownload": false,
          "useMediaDownloadService": false,
          "supportsSubscription": false,
          "supportsMediaUpload": false
        }
      }
    }
  },
  "methods": {}
}